begin;
create temp table review_qa as select
 (select p.id from public.profiles p where p.account_status='active' and exists(select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='traveler') and not exists(select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name in ('admin','business_owner')) limit 1) traveler,
 (select o.profile_id from public.business_owners o join public.profiles p on p.id=o.profile_id where p.account_status='active' and not exists(select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='admin') limit 1) owner,
 (select p.id from public.profiles p join public.profile_roles pr on pr.profile_id=p.id join public.roles r on r.id=pr.role_id where r.name='admin' and p.account_status='active' limit 1) administrator,
 gen_random_uuid() destination,gen_random_uuid() hotel,gen_random_uuid() restaurant,gen_random_uuid() attraction,gen_random_uuid() booking,gen_random_uuid() slot,gen_random_uuid() table_booking;
create temp table review_qa_results(label text);
grant select on review_qa to authenticated,anon;grant select,insert on review_qa_results to authenticated,anon;
insert into public.destinations(id,category_id,name,province,slug) select q.destination,d.category_id,'QA review destination','QA','qa-review-'||q.destination from review_qa q cross join lateral(select category_id from public.destinations limit 1)d;
insert into public.business_listings(id,owner_id,destination_id,name,slug,listing_type,status) select v.id,o.id,q.destination,'QA review '||v.kind,'qa-'||v.id,v.kind,'approved' from review_qa q join public.business_owners o on o.profile_id=q.owner cross join lateral(values(q.hotel,'hotel'),(q.restaurant,'restaurant'),(q.attraction,'attraction'))v(id,kind);
insert into public.hotels(hotel_id,check_in_time,check_out_time) select hotel,'14:00','11:00' from review_qa;
insert into public.restaurants(restaurant_id,operating_hours,reservation_fee) select restaurant,'09:00–20:00',100 from review_qa;
insert into public.attractions(attraction_id,entrance_fee) select attraction,0 from review_qa;
insert into public.bookings(id,profile_id,booking_type,guest_name,guest_email,guest_count,total_amount,status,payment_status,idempotency_key) select booking,traveler,'hotel','QA','qa@example.test',1,100,'confirmed','paid','qa-'||booking from review_qa union all select table_booking,traveler,'restaurant','QA','qa@example.test',1,100,'confirmed','paid','qa-'||table_booking from review_qa;
insert into public.hotel_bookings(booking_id,hotel_id,check_in,check_out) select booking,hotel,current_date-3,current_date-1 from review_qa;
insert into public.restaurant_slots(id,restaurant_id,starts_at,ends_at,capacity) select slot,restaurant,now()-interval '2 days',now()-interval '1 day',10 from review_qa;
insert into public.restaurant_bookings(booking_id,slot_id) select table_booking,slot from review_qa;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select traveler::text from review_qa),true);
do $$ declare q review_qa; rid uuid; rejected boolean; begin select * into q from review_qa;
 rid:=public.save_traveler_review(q.destination,null,5,'A lovely destination to explore.');
 perform public.save_traveler_review(q.destination,null,4,'Updated destination experience.');
 if (public.place_reviews(q.destination,null,0)->>'total')::int<>1 then raise exception 'Duplicate destination review';end if;
 perform public.save_traveler_review(null,q.attraction,5,'A lovely independent attraction visit.');
 if (public.place_reviews(null,q.attraction,0)->'items'->0->>'verified')::boolean then raise exception 'Unbooked visit falsely verified';end if;
 insert into review_qa_results values('Destination/attraction reviews without booking; updates do not duplicate');
 rejected:=false;begin perform public.save_traveler_review(null,q.hotel,5,'Cannot review a confirmed stay yet.');exception when others then rejected:=true;end;if not rejected then raise exception 'Confirmed booking accepted';end if;
 rejected:=false;begin perform public.complete_owner_booking(q.booking);exception when others then rejected:=true;end;if not rejected then raise exception 'Traveler completed own booking';end if;
 rejected:=false;begin perform public.save_traveler_review(q.destination,null,6,'Invalid stars rejected');exception when others then rejected:=true;end;if not rejected then raise exception 'Invalid rating accepted';end if;
 rejected:=false;begin update public.reviews set rating=5 where id=rid;exception when insufficient_privilege then rejected:=true;end;if not rejected then raise exception 'Direct review write allowed';end if;
 if has_column_privilege('authenticated','public.reviews','booking_id','select') then raise exception 'Booking IDs exposed';end if;
 insert into review_qa_results values('Confirmed booking, traveler completion, invalid rating and direct write denied; booking references private');
end $$;
select set_config('request.jwt.claim.sub',(select administrator::text from review_qa),true);
do $$ declare q review_qa; rejected boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(q.destination,null,5,'An administrator should not review');exception when others then rejected:=true;end;if not rejected then raise exception 'Staff review accepted';end if;end $$;
select set_config('request.jwt.claim.sub',(select owner::text from review_qa),true);
do $$ declare q review_qa;begin select * into q from review_qa;perform public.complete_owner_booking(q.booking);perform public.complete_owner_booking(q.table_booking);perform public.complete_owner_booking(q.booking);insert into review_qa_results values('Owner completes elapsed paid hotel and restaurant visits, idempotently');end $$;
select set_config('request.jwt.claim.sub',(select traveler::text from review_qa),true);
do $$ declare q review_qa;begin select * into q from review_qa;perform public.save_traveler_review(null,q.hotel,5,'A wonderful completed hotel stay.');perform public.save_traveler_review(null,q.restaurant,4,'A delicious meal after my reservation.');if not (public.place_reviews(null,q.hotel,0)->'items'->0->>'verified')::boolean or not (public.place_reviews(null,q.restaurant,0)->'items'->0->>'verified')::boolean then raise exception 'Completed visits not verified';end if;insert into review_qa_results values('Completed visits verified for hotel and restaurant');end $$;
reset role;
update public.bookings set profile_id=(select owner from review_qa) where id=(select booking from review_qa);
set local role authenticated;
do $$ declare q review_qa;denied boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(null,q.hotel,5,'Cannot use another travelers booking');exception when others then denied:=true;end;if not denied then raise exception 'Foreign booking accepted';end if;insert into review_qa_results values('Another account booking cannot unlock a review');end $$;
reset role;
update public.bookings set profile_id=(select traveler from review_qa),status='cancelled' where id=(select booking from review_qa);
set local role authenticated;
do $$ declare q review_qa; rejected boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(null,q.hotel,5,'Cannot use cancelled booking');exception when others then rejected:=true;end;if not rejected then raise exception 'Cancelled accepted';end if;end $$;
reset role;
update public.bookings set status='completed',payment_status='pending' where id=(select booking from review_qa);
set local role authenticated;
do $$ declare q review_qa;rejected boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(null,q.hotel,5,'Cannot use unpaid booking');exception when others then rejected:=true;end;if not rejected then raise exception 'Unpaid accepted';end if;end $$;
reset role;
update public.bookings set status='confirmed',payment_status='paid' where id=(select booking from review_qa);
update public.hotel_bookings set check_in=current_date+1,check_out=current_date+2 where booking_id=(select booking from review_qa);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select owner::text from review_qa),true);
do $$ declare q review_qa;rejected boolean:=false;begin select * into q from review_qa;begin perform public.complete_owner_booking(q.booking);exception when others then rejected:=true;end;if not rejected then raise exception 'Future completion allowed';end if;end $$;
reset role;
update public.bookings set status='completed' where id=(select booking from review_qa);
set local role authenticated;
select set_config('request.jwt.claim.sub',(select traveler::text from review_qa),true);
do $$ declare q review_qa;rejected boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(null,q.hotel,5,'Cannot review a future completed stay');exception when others then rejected:=true;end;if not rejected then raise exception 'Future review allowed';end if;end $$;
reset role;
update public.reviews set status='hidden' where destination_id=(select destination from review_qa);
set local role authenticated;
do $$ declare q review_qa;rejected boolean:=false;begin select * into q from review_qa;begin perform public.save_traveler_review(q.destination,null,5,'Cannot republish hidden review');exception when others then rejected:=true;end;if not rejected then raise exception 'Hidden republished';end if;insert into review_qa_results values('Cancelled, unpaid and future bookings denied; hidden moderation preserved');end $$;
reset role;
set local role anon;
select set_config('request.jwt.claim.sub','',true);
do $$ declare q review_qa;begin select * into q from review_qa;if (public.place_reviews(null,q.restaurant,0)->>'total')::int<>1 then raise exception 'Public feed failed';end if;if has_function_privilege('anon','public.save_traveler_review(uuid,uuid,integer,text)','execute') or has_function_privilege('anon','public.complete_owner_booking(uuid)','execute') or has_function_privilege('authenticated','travelmate_ui.review_booking(uuid,uuid)','execute') then raise exception 'Unsafe grants';end if;insert into review_qa_results values('Anonymous feed readable; anonymous writes and internal helpers denied');end $$;
select * from review_qa_results;
rollback;

