// Edit the HTML in the template string. Ids used by main.ts must stay the same.
export const accountPage = `<section data-page="account" class="profile-page" hidden>
<div class="account-heading"><p class="eyebrow">YOUR ACCOUNT</p><h1>Account settings</h1><p>Keep your details up to date.</p></div>
<div id="notice" role="status" aria-live="polite">Checking configuration…</div>
<div id="account" hidden>
  <div class="account-top"><div class="account-identity"><span class="account-identity-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></svg></span><div><span class="account-email-label">Signed in as</span><p id="email"></p><span id="account-type" class="badge"></span></div></div><button id="refresh" class="quiet" type="button"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/></svg>Reload profile</button></div>
  <p id="owner-note" class="owner-note" hidden>Manage your listings and reservations in your business workspace.</p><span id="uid" hidden></span><span id="profile-id" hidden></span>
  <div id="react-appearance" class="tm-react"></div>
  <div class="account-settings-grid">
    <div class="account-details-card"><div class="account-section-heading"><h2>Personal details</h2><p>Your name and contact information for TravelMate.</p></div>
      <form id="profile-form"><fieldset id="fields" disabled><div class="account-field"><label for="name">Full name</label><input id="name" required maxlength="150" autocomplete="name"></div><div class="account-field"><label for="phone">Contact number <span>(optional)</span></label><input id="phone" type="tel" maxlength="30" autocomplete="tel" placeholder="+63 900 000 0000"></div><div class="account-field"><label for="address">Address <span>(optional)</span></label><textarea id="address" maxlength="255" rows="3" autocomplete="street-address" placeholder="City, province or address"></textarea></div><div class="account-save-row"><span>Review your changes before saving.</span><button id="save" class="primary" type="submit">Save profile <span aria-hidden="true">→</span></button></div></fieldset></form>
    </div>
    <aside class="account-side-panels" aria-label="Photo and travel preferences"><div class="avatar-area"><div class="account-section-heading"><h2>Profile photo</h2><p>A familiar face for your account.</p></div><div class="portrait"><img id="avatar" alt="Your avatar" hidden><span id="avatar-placeholder">TM</span></div><div class="avatar-copy"><p class="hint">JPG, PNG or WebP · Up to 2 MB<br>Only visible to you.</p><div class="file-row"><input id="file" class="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled><label class="file-btn" for="file">Choose image</label><span id="file-name">No file chosen</span></div><button id="upload" class="primary" type="button" disabled>Upload photo</button><p id="object-path" hidden></p></div></div>
    <a id="travel-preferences-link" class="account-preferences" href="#/preferences" hidden><span class="eyebrow">MAKE IT YOURS</span><strong>Travel preferences <span aria-hidden="true">↗</span></strong><span>Update your interests and travel pace for personal recommendations.</span></a></aside>
  </div>
</div></section>`;
