// Edit the HTML in the template string. Ids used by main.ts must stay the same.
export const accountPage = `<section data-page="account" class="profile-page" hidden><div class="intro"><p class="eyebrow">YOUR TRAVELMATE ACCOUNT</p><h1>A little setup.<br>A world to explore.</h1><p>Your profile, your places, your next journey.</p></div>
<div class="card"><div id="notice" role="status" aria-live="polite">Checking configuration…</div>
<div id="account" hidden><div class="account-top"><div><p class="eyebrow">SIGNED IN</p><p id="email"></p><span id="account-type" class="badge"></span></div><button id="logout" class="quiet">Sign out</button></div>
<p id="owner-note" class="owner-note" hidden>Business Owner account. Tools to manage hotel, restaurant, attraction and transport listings are planned for a later batch — for now you can manage your profile.</p><span id="uid" hidden></span><span id="profile-id" hidden></span>
<button id="refresh" class="quiet">Reload profile</button>
<form id="profile-form"><fieldset id="fields" disabled><label for="name">Full name</label><input id="name" required maxlength="150" autocomplete="name"><label for="address">Address (optional)</label><textarea id="address" maxlength="255" rows="3" autocomplete="street-address"></textarea><label for="phone">Contact number (optional)</label><input id="phone" type="tel" maxlength="30" autocomplete="tel" placeholder="+63 900 000 0000"><button id="save" class="primary" type="submit">Save profile</button></fieldset></form>
<div class="avatar-area"><div class="portrait"><img id="avatar" alt="Your avatar" hidden><span id="avatar-placeholder">TM</span></div><div class="avatar-copy"><h3>Profile photo</h3><p class="hint">JPEG, PNG or WebP · up to 2 MB · kept private to you</p><div class="file-row"><input id="file" class="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled><label class="file-btn" for="file">Choose image</label><span id="file-name">No file chosen</span></div><button id="upload" class="primary" disabled>Upload photo</button><p id="object-path" hidden></p></div></div>
</div></div></section>`;
