// Signed-in home page (copies the prototype's Home: headline, search, photo, feature tiles, reviews).
const IMG = 'https://upload.wikimedia.org/wikipedia/commons/8/86/El_Nido_Palawan_Big_Lagoon.jpg';
const ico = (d: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${d}</svg>`;
export const homePage = `<section data-page="home" class="home" hidden>
<div id="workspace-home" class="journey-page" hidden><p class="eyebrow">YOUR WORKSPACE</p><h1 id="workspace-title"></h1><p class="lead" id="workspace-description"></p><a id="workspace-action" class="button primary" href="#/owner">Open workspace →</a><div id="workspace-summary" class="dashboard-summary" aria-live="polite"></div><div class="journey-panel workspace-empty"><p class="eyebrow">ENGAGEMENT ANALYTICS</p><h2>Good decisions start with real data.</h2><p>Website visits and listing clicks are not tracked yet. Your listing and review summaries above use current database records.</p></div><a href="#/trips">Plan a personal trip →</a></div><div id="traveler-home"><div class="planner-banner"><div><p class="eyebrow">LESS PLANNING. MORE POSSIBILITY.</p><h1>Every great trip<br>starts with <em>a plan.</em></h1><p>Set your destination, dates and travel style.<br>Keep the details of your next adventure together.</p><a class="button primary" href="#/trips">Plan my trip →</a><a class="planner-secondary" href="#/explore">Find inspiration</a></div><div class="journey-art" aria-hidden="true"><span>YOUR NEXT ADVENTURE</span><div class="ticket-art"><small>TRAVELMATE / TRIP BRIEF</small><strong>Somewhere<br>new awaits.</strong><hr><p>ARRIVE · EXPLORE · RETURN</p></div><span>TAKE THE SCENIC ROUTE ↗</span></div></div><div id="traveler-summary" class="dashboard-summary" aria-live="polite"></div><div class="h-hero"><div class="h-copy"><p class="eyebrow">WELCOME BACK, <span id="hm-name">TRAVELER</span></p>
<h1>Find your next<br><span class="accent">favorite place.</span></h1>
<p class="lead">Explore the approved catalog, then build a day-by-day plan around the places that interest you.</p>
<form id="home-search-form" class="ticket"><div class="ticket-field"><label for="home-search">Destination or province</label><input id="home-search" type="search" placeholder="Try “Bauang”, “San Juan” or “La Union”"></div><button class="primary" type="submit">Search →</button></form>
<div class="h-chips"><span><b id="hm-dest">–</b> destinations</span><span><b id="hm-stay">–</b> places to stay</span><span><b id="hm-eat">–</b> places to eat</span></div></div>
<div class="h-photo"><img src="${IMG}" alt="Big Lagoon, El Nido, Palawan" loading="eager"><span id="hm-rate" hidden></span><div class="h-caption">BIG LAGOON, EL NIDO · PHOTO: WIKIMEDIA COMMONS</div></div></div>
<div class="h-tiles">
<a class="tile" href="#/explore">${ico('<circle cx="12" cy="10" r="3"/><path d="M12 21s7-6.7 7-11.5A7 7 0 0 0 5 9.5C5 14.3 12 21 12 21z"/>')}<h3>Where to go</h3><p>Destinations across the archipelago, from limestone lagoons to rice terraces.</p><span class="go">Browse destinations →</span></a>
<a class="tile" href="#/stay">${ico('<path d="M3 19V7a1 1 0 0 1 1-1h5v13M3 19h18M9 19V6M9 10h5a2 2 0 0 1 2 2v7M20 19v-4a2 2 0 0 0-2-2h-2"/>')}<h3>Where to sleep</h3><p>Hotels, resorts and homestays, beachfront to backpacker, side by side.</p><span class="go">Browse hotels →</span></a>
<a class="tile" href="#/eat">${ico('<path d="M6 2v7a2 2 0 0 0 2 2v11M6 2v20M10 2v9M18 2c-2 0-3 2-3 5v3h6M18 2v20"/>')}<h3>Where to eat</h3><p>Local kitchens and cafés with menus, hours and cuisines.</p><span class="go">Browse restaurants →</span></a>
<a class="tile" href="#/attractions">${ico('<path d="M12 3l2.8 5.7 6.2.9-4.5 4.4 1 6.2L12 17.3 6.5 20.2l1-6.2L3 9.6l6.2-.9z"/>')}<h3>Things to do</h3><p>Gardens, tours and sights with entrance fees and schedules.</p><span class="go">Browse attractions →</span></a>
</div>
<section class="band" id="home-reviews" hidden><p class="eyebrow">WHAT TRAVELERS SAY</p><h2>Straight from people who went</h2><label class="review-filter">Filter recent reviews<select id="home-review-rating"><option value="all">All ratings</option><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><p class="muted">Latest traveler opinions. Open a place to see its reviews and Verified booking badges.</p><div class="l-grid" id="home-review-grid"></div></section>
</div></section>`;
