// Edit the HTML in the template string. Ids used by main.ts must stay the same.
export const landingPage = `<section data-page="landing">
<div class="l-hero"><div class="l-hero-in"><p class="eyebrow light">PHILIPPINE EDITION · TRAVEL GUIDE &amp; TRIP PLANNER</p><h1>Discover the Philippines, one trip at a time.</h1><p class="lead">Find where to go, where to stay and where to eat — then keep it all in one place. Free to join.</p><div class="cta-row"><a class="btn primary lg" href="#/register">Get started — it's free</a><a class="btn ghost lg" href="#/login">Log in</a></div><p class="trust">✓ Community reviews &nbsp; ✓ Save places you love &nbsp; ✓ Built for travelers and local businesses</p></div></div>
<section class="stats" id="stats" hidden><div><strong id="st-dest">–</strong><span>Destinations</span></div><div><strong id="st-stay">–</strong><span>Places to stay</span></div><div><strong id="st-eat">–</strong><span>Places to eat</span></div><div><strong id="st-rate">–</strong><span>Average of latest 100 reviews</span></div></section>
<section class="why" id="why"><p class="eyebrow">WHY TRAVELMATE</p><h2>Everything you need before you book a ticket.</h2><div class="feat-grid"><div><span class="ico">⌖</span><h3>Explore destinations</h3><p>Islands, highlands and cities, each with things to do and places to stay and eat.</p></div><div><span class="ico">★</span><h3>Community reviews</h3><p>Read community ratings and opinions alongside listing details. Visits are not independently verified.</p></div><div><span class="ico">♡</span><h3>Save and plan</h3><p>Keep a wishlist of places, then come back to it when you are ready to go.</p></div><div><span class="ico">⌂</span><h3>Support local business</h3><p>Hotels, restaurants and attractions managed by the people who run them.</p></div></div></section>
<section class="band" id="reviews" hidden><p class="eyebrow">WHAT TRAVELERS SAY</p><h2>From the community</h2><div class="l-grid" id="review-grid"></div></section>
<section class="owner-band"><div><p class="eyebrow">FOR BUSINESS OWNERS</p><h2>List your business on TravelMate.</h2><p>Run a hotel, restaurant or attraction? Create a free account, choose Business Owner, and reach travelers planning a trip to your destination.</p></div><a class="btn primary lg" href="#/register">Register your business →</a></section>
<section class="cta-band"><h2>Your next trip starts here.</h2><p>Create an account and start planning at your own pace.</p><a class="btn primary lg" href="#/register">Get started — it's free</a></section>
</section>`;
