import type { SupabaseClient } from '@supabase/supabase-js';
import {buildItinerary,type Brief,type Stop,type Venue} from './itinerary-engine';
export const itineraryMarkup=`<dialog id="itinerary-dialog" class="itinerary-dialog"><button type="button" id="itinerary-close">Close</button><p class="eyebrow">YOUR JOURNEY, DAY BY DAY</p><h2 id="itinerary-title"></h2><p id="itinerary-budget"></p><p class="itinerary-disclaimer">Planning proposal, not a booking. Visit durations and transfer allowances are estimates; opening hours, routes and costs are not verified. Your budget is a target, not a quoted total.</p><div class="flex gap-4"><button id="itinerary-generate" class="primary" type="button">Generate preview</button><button id="itinerary-save" type="button" disabled>Save this itinerary</button></div><p id="itinerary-message" role="status" aria-live="polite"></p><div id="itinerary-days"></div></dialog><dialog id="itinerary-replace"><form method="dialog"><h2>Save this schedule?</h2><p>This will replace all existing itinerary items for this trip, including manually added items. It will not make bookings or payments.</p><div class="flex gap-4"><button value="cancel">Keep existing</button><button value="save" class="primary">Save schedule</button></div></form></dialog>`;
const briefColumns='id,name,destination_id,start_date,end_date,arrival_time,departure_time,travel_pace,interests,budget,budget_currency,updated_at,status';
export function initItinerary(client:SupabaseClient){
 const db=client.schema('public'), dialog=document.querySelector<HTMLDialogElement>('#itinerary-dialog')!,confirm=document.querySelector<HTMLDialogElement>('#itinerary-replace')!,days=document.querySelector<HTMLElement>('#itinerary-days')!,message=document.querySelector<HTMLElement>('#itinerary-message')!,generate=document.querySelector<HTMLButtonElement>('#itinerary-generate')!,save=document.querySelector<HTMLButtonElement>('#itinerary-save')!;
 let epoch=0,brief:(Brief&{status:string})|null=null,preview:Stop[]|null=null,busy=false;
 const say=(s:string,error=false)=>{message.textContent=s;message.classList.toggle('error',error)};
 const controls=()=>{generate.disabled=busy||!brief||brief.status!=='draft';save.disabled=busy||!preview||!brief||brief.status!=='draft';};
 const fail=(e:unknown)=>say(e&&typeof e==='object'&&'message' in e?String(e.message):String(e),true);
 const node=(tag:string,text:string,cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n};
 function render(stops:Stop[]){days.replaceChildren();if(!stops.length){days.append(node('p','No saved itinerary yet. Generate a preview from the approved catalog.'));return;}let date='';let section:HTMLElement;for(const item of stops){if(item.planned_date!==date){date=item.planned_date;section=node('section','','itinerary-day');section.append(node('h3',date));days.append(section);}const card=node('article','','itinerary-stop');card.append(node('time',`${item.planned_time.slice(0,5)}–${(item.planned_end_time??item.planned_time).slice(0,5)}`),node('h4',item.activity),node('p',item.recommendation_reason??'Saved itinerary activity.'),node('small',item.notes??''));section!.append(card);}}
 function clear(){epoch++;brief=null;preview=null;busy=false;days.replaceChildren();say('');document.querySelector('#itinerary-title')!.textContent='';document.querySelector('#itinerary-budget')!.textContent='';if(confirm.open)confirm.close('cancel');if(dialog.open)dialog.close();controls();}
 async function open(id:string){clear();const ticket=epoch;dialog.showModal();busy=true;controls();say('Loading your trip…');try{const t=await db.from('trips').select(briefColumns).eq('id',id).single();if(ticket!==epoch)return;if(t.error)throw t.error;brief=t.data as Brief&{status:string};document.querySelector('#itinerary-title')!.textContent=brief.name;document.querySelector('#itinerary-budget')!.textContent=`${brief.start_date??'No date'} → ${brief.end_date??'No date'} · Budget target: ${brief.budget_currency??''} ${brief.budget??'Not set'}`;const rows=await db.from('trip_items').select('planned_date,planned_time,planned_end_time,activity,listing_id,recommendation_reason,notes').eq('trip_id',id).order('sequence_number');if(ticket!==epoch)return;if(rows.error)throw rows.error;const scheduled=(rows.data??[]).filter(x=>x.planned_date&&x.planned_time) as Stop[];render(scheduled);say(rows.data?.length!==scheduled.length?'Some older items have no scheduled date/time and are not displayed. Saving a new schedule replaces those items too.':brief.status==='draft'?'Saved schedule loaded. Generate a preview to propose a new schedule.':'This trip is read-only.');}catch(e){if(ticket===epoch)fail(e);}finally{if(ticket===epoch){busy=false;controls();}}}
 generate.onclick=async()=>{if(!brief||busy)return;const t=brief,ticket=epoch;busy=true;preview=null;controls();say('Finding approved places…');try{if(!t.destination_id||!t.start_date||!t.end_date||!t.arrival_time||!t.departure_time)throw Error('Open the draft and complete the destination, dates and arrival/departure times first.');const r=await db.from('business_listings').select('id,name,listing_type,description,address').eq('destination_id',t.destination_id).eq('status','approved').in('listing_type',['restaurant','attraction']).order('name').limit(200);if(ticket!==epoch)return;if(r.error)throw r.error;if(!r.data?.length)throw Error('This destination has no approved restaurants or attractions yet. Add and approve real catalog entries before generating recommendations.');preview=buildItinerary(t,r.data as Venue[]);render(preview);say('Unsaved preview. Flexible periods mean the catalog or available time could not support another suggestion. Review the estimates before saving.');}catch(e){if(ticket===epoch)fail(e);}finally{if(ticket===epoch){busy=false;controls();}}};
 save.onclick=async()=>{if(!brief||!preview||busy)return;const ticket=epoch,t=brief,items=preview;confirm.returnValue='cancel';confirm.showModal();const result=await new Promise<string>(resolve=>confirm.addEventListener('close',()=>resolve(confirm.returnValue),{once:true}));if(result!=='save'||ticket!==epoch)return;busy=true;controls();try{const r=await db.rpc('save_my_itinerary',{p_trip:t.id,p_expected_updated_at:t.updated_at,p_items:items});if(ticket!==epoch)return;if(r.error)throw r.error;brief.updated_at=r.data;preview=null;say('Itinerary saved. Close and reopen this trip to see the saved schedule.');}catch(e){if(ticket===epoch)fail(e);}finally{if(ticket===epoch){busy=false;controls();}}};
 document.querySelector<HTMLButtonElement>('#itinerary-close')!.onclick=clear;dialog.addEventListener('cancel',e=>{e.preventDefault();clear();});return {open,clear};
}
