import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, BedDouble, Utensils, Compass, MapPin, CalendarDays, Plus, Clock3, Users } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import { client, useIdentity, currentIdentity, navigate, errorMessage, money, photosFor, track, type Listing, type Destination } from './state';
import { EmptyState, ErrorState, ListingCard, LoadingCards } from './shared';
import { destinationPhoto } from './destination-photos';
import { DestinationCover, PhotoCredit } from './destination-picture';
import { destinationDescription } from '../destination-copy';
export type Room = { id: string; room_number: string; room_type: string; max_guests: number; base_nightly_rate: number; operational_status: string };
export type Slot = { id: string; starts_at: string; ends_at: string; capacity: number };
export function planDestination(id: string) { sessionStorage.setItem('travelmate:plan-destination', id); if (currentIdentity().role === 'guest') { sessionStorage.setItem('travelmate:entry-intent', 'traveler'); navigate('/register/traveler'); return; } navigate('/trips'); window.dispatchEvent(new Event('travelmate:new-trip')); }
export function DestinationPage({ id }: { id: string }) {
  const identity = useIdentity(); const [destination, setDestination] = useState<Destination | null>(null); const [listings, setListings] = useState<Listing[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { let cancelled = false; setLoading(true); setError(''); setDestination(null); setListings([]);
    void (async () => { try { const [d, l] = await Promise.all([client.from('destinations').select('id,name,province,description').eq('id', id).eq('is_active', 1).single(), client.from('business_listings').select('id,name,listing_type,description,address,destination_id').eq('destination_id', id).eq('status', 'approved').order('name').limit(200)]); if (d.error) throw d.error; if (l.error) throw l.error; const places = await photosFor(l.data as Listing[]); if (!cancelled) { setDestination(d.data); setListings(places); } } catch (e) { if (!cancelled) setError(errorMessage(e)); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; };
  }, [id, identity.id, version]);
  const categories = [{ type: 'hotel', label: 'Places to sleep', icon: BedDouble }, { type: 'restaurant', label: 'Places to eat', icon: Utensils }, { type: 'attraction', label: 'Things to do', icon: Compass }];
  return <div className="tm-page"><Button variant="ghost" onClick={() => navigate(identity.role === 'guest' ? '/' : '/explore')}><ArrowLeft />All destinations</Button>{error ? <ErrorState message={error} retry={() => setVersion(x => x + 1)} /> : loading ? <LoadingCards /> : destination && <><div className="tm-destination-hero"><div><p className="tm-eyebrow"><MapPin size={14} />{destination.province}</p><h1>A day or two<br />in <em>{destination.name}.</em></h1><p>{destinationDescription(destination.description) || 'Find your home for the night, your next favorite meal, and something worth exploring.'}</p><Button size="lg" onClick={() => planDestination(destination.id)}><Plus />Create an itinerary here<ArrowUpRight /></Button></div><div className="tm-destination-hero-photo"><DestinationCover key={destination.id} photo={destinationPhoto(destination.name,destination.province)}/><PhotoCredit photo={destinationPhoto(destination.name,destination.province)}/></div></div><Tabs defaultValue="all" key={id}><TabsList aria-label="Destination listings"><TabsTrigger value="all">All places <span className="tm-tab-count">{listings.length}</span></TabsTrigger>{categories.map(({ type, label, icon: Icon }) => <TabsTrigger value={type} key={type}><Icon size={15} />{label}<span className="tm-tab-count">{listings.filter(l => l.listing_type === type).length}</span></TabsTrigger>)}</TabsList>{['all', ...categories.map(x => x.type)].map(type => <TabsContent value={type} key={type}>{categories.filter(c => type === 'all' || c.type === type).map(({ type: kind, label, icon: Icon }) => <section className="tm-destination-section" key={kind}><div className="tm-section-title"><h2><Icon size={22} />{label}</h2><span className="tm-muted">{destination.name}</span></div>{listings.some(l => l.listing_type === kind) ? <div className="tm-card-grid">{listings.filter(l => l.listing_type === kind).map(listing => <ListingCard key={listing.id} listing={listing} />)}</div> : <EmptyState title={'No approved ' + (kind === 'hotel' ? 'stays' : kind === 'restaurant' ? 'restaurants' : 'attractions') + ' yet'}>New businesses appear here after administrator approval. You can still start your trip plan.</EmptyState>}</section>)}</TabsContent>)}</Tabs><p className="tm-data-note">Only approved listings assigned to this destination are shown.{listings.length === 200 ? ' Showing the first 200 places by name.' : ''} Attractions have schedules and entrance fees; online attraction tickets are not configured.</p></>}</div>;
}

type Detail = { listing: Listing; rooms: Room[]; slots: Slot[]; checkIn?: string; checkOut?: string; hours?: string; reservationFee?: number; entranceFee?: number; menu: { id: string; name: string; price: number; category: string }[]; schedules: { operating_day: string; schedule_text: string }[]; amenities: string[]; cuisines: string[] };
function names(rows: unknown[]) { return rows.map(row => { const value = Object.values(row as Record<string, unknown>)[0]; return Array.isArray(value) ? value[0]?.name : (value as { name?: string } | null)?.name; }).filter(Boolean) as string[]; }
export async function listingDetail(id: string): Promise<Detail> {
  const { data: listing, error } = await client.from('business_listings').select('id,name,listing_type,description,address,destination_id').eq('id', id).eq('status', 'approved').single(); if (error) throw error;
  const result: Detail = { listing: (await photosFor([listing as Listing]))[0], rooms: [], slots: [], menu: [], schedules: [], amenities: [], cuisines: [] };
  const checked = <T,>(r: { data: T; error: unknown }) => { if (r.error) throw r.error; return r.data; };
  if (listing.listing_type === 'hotel') { const [h, r, a] = await Promise.all([client.from('hotels').select('check_in_time,check_out_time').eq('hotel_id', id).single(), client.from('rooms').select('id,room_number,room_type,max_guests,base_nightly_rate,operational_status').eq('hotel_id', id).order('base_nightly_rate'), client.from('hotel_amenities').select('amenities(name)').eq('hotel_id', id)]); const hotel = checked(h); result.checkIn = hotel?.check_in_time; result.checkOut = hotel?.check_out_time; result.rooms = checked(r) ?? []; result.amenities = names(checked(a) ?? []); }
  else if (listing.listing_type === 'restaurant') { const [r, m, s, c] = await Promise.all([client.from('restaurants').select('operating_hours,reservation_fee').eq('restaurant_id', id).single(), client.from('menu_items').select('id,name,price,category').eq('restaurant_id', id).eq('is_available', 1).order('category'), client.from('restaurant_slots').select('id,starts_at,ends_at,capacity').eq('restaurant_id', id).eq('is_open', 1).gt('starts_at', new Date().toISOString()).order('starts_at').limit(100), client.from('restaurant_cuisines').select('cuisines(name)').eq('restaurant_id', id)]); const restaurant = checked(r); result.hours = restaurant?.operating_hours; result.reservationFee = restaurant?.reservation_fee; result.menu = checked(m) ?? []; result.slots = checked(s) ?? []; result.cuisines = names(checked(c) ?? []); }
  else { const [a, s] = await Promise.all([client.from('attractions').select('entrance_fee').eq('attraction_id', id).single(), client.from('attraction_schedules').select('operating_day,schedule_text').eq('attraction_id', id)]); result.entranceFee = checked(a)?.entrance_fee; result.schedules = checked(s) ?? []; }
  return result;
}
export function ListingPage({ id }: { id: string }) {
  const identity = useIdentity(); const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(''); const [version, setVersion] = useState(0);
  const reserve = (path: string) => { if (identity.role === 'guest') { sessionStorage.setItem('travelmate:entry-intent', 'traveler'); navigate('/register/traveler'); } else navigate(path); };
  useEffect(() => { let cancelled = false; setData(null); setError(''); void listingDetail(id).then(result => { if (!cancelled) { setData(result); void track('listing_view', id); } }).catch(e => { if (!cancelled) setError(errorMessage(e)); }); return () => { cancelled = true; }; }, [id, identity.id, version]);
  if (error) return <div className="tm-page"><ErrorState message={error} retry={() => setVersion(x => x + 1)} /></div>;
  if (!data) return <div className="tm-page"><LoadingCards /></div>;
  const { listing: l } = data;
  return <div className="tm-page"><Button variant="ghost" onClick={() => navigate('/destination/' + l.destination_id)}><ArrowLeft />Back to destination</Button><div className="tm-listing-hero"><div className={'tm-listing-photo tm-cover-' + l.listing_type}>{l.image ? <img src={l.image} alt={l.name} onError={e => { e.currentTarget.hidden = true; }} /> : <Compass size={90} strokeWidth={1} />}<span className="tm-pill">Approved local listing</span></div><div><p className="tm-eyebrow">{l.listing_type === 'hotel' ? 'MAKE YOURSELF AT HOME' : l.listing_type === 'restaurant' ? 'A TASTE OF SOMETHING LOCAL' : 'TAKE THE SCENIC ROUTE'}</p><h1>{l.name}</h1><p className="tm-place-address"><MapPin size={16} />{l.address || 'Contact the business for directions'}</p><p className="tm-description">{l.description}</p><div className="tm-detail-tags">{[...data.amenities, ...data.cuisines].map(x => <span className="tm-pill" key={x}>{x}</span>)}</div>{l.listing_type === 'hotel' && <p className="tm-detail-hours"><Clock3 size={17} />Check-in {data.checkIn?.slice(0, 5)} · Check-out {data.checkOut?.slice(0, 5)}</p>}{l.listing_type === 'restaurant' && <><p className="tm-detail-hours"><Clock3 size={17} />{data.hours || 'Confirm opening hours with the business'}</p><p>Reservation fee: <strong>{money(data.reservationFee ?? 0)}</strong></p><Button disabled={!data.slots.length} onClick={() => reserve('/book/' + id)}>Reserve a table<ArrowUpRight /></Button>{!data.slots.length && <p className="tm-data-note">No upcoming reservation slots. The owner needs to add availability.</p>}</>}{l.listing_type === 'attraction' && <><p>Entrance fee: <strong>{money(data.entranceFee ?? null)}</strong></p><Button onClick={() => planDestination(l.destination_id)}>Plan a visit<Plus /></Button></>}</div></div>
    {l.listing_type === 'hotel' && <><div className="tm-section-title"><h2>Find your room</h2><span className="tm-muted">Rates in Philippine pesos · per night</span></div><div className="tm-card-grid">{data.rooms.map(room => <Card key={room.id}><CardContent className="p-6"><div className="tm-room-icon"><BedDouble size={28} /></div><h3>{room.room_type}</h3><p className="tm-muted">Room {room.room_number}</p><p className="tm-detail-hours"><Users size={16} />Up to {room.max_guests} guests</p><strong className="tm-room-price">{money(room.base_nightly_rate)}<small> / night</small></strong><Button className="mt-5 w-full" disabled={room.operational_status !== 'available'} onClick={() => reserve('/book/' + id + '?room=' + room.id)}>{room.operational_status === 'available' ? 'Check dates & reserve' : room.operational_status}<ArrowUpRight /></Button><p className="tm-data-note">Date availability is checked when reserving.</p></CardContent></Card>)}</div></>}
    {l.listing_type === 'restaurant' && <Card><CardContent className="p-6"><h2>On the menu</h2>{data.menu.map(item => <div className="tm-menu-row" key={item.id}><span><strong>{item.name}</strong><small>{item.category}</small></span><strong>{money(item.price)}</strong></div>)}{!data.menu.length && <p className="tm-muted">No available menu items yet.</p>}</CardContent></Card>}
    {l.listing_type === 'attraction' && <Card><CardContent className="p-6"><h2>When to visit</h2>{data.schedules.map((schedule, i) => <div className="tm-menu-row" key={i}><strong>{schedule.operating_day}</strong><span>{schedule.schedule_text}</span></div>)}<p className="tm-data-note">Confirm hours and entrance fees with the business before visiting.</p></CardContent></Card>}
  </div>;
}
