import {useEffect,useState,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart} from 'lucide-react';
import {client,useIdentity,currentIdentity,navigate,errorMessage} from './state';
let owner:string|null=null,keys=new Set<string>(),snapshot:string[]=[],ready=false,promise:Promise<void>|null=null;
const subscribers=new Set<()=>void>();
function publish(){snapshot=[...keys];subscribers.forEach(fn=>fn());window.dispatchEvent(new Event('travelmate:favorites'));}
export function isSaved(listing:string){return keys.has('l:'+listing);}
function load(id:string|null){if(id!==owner){owner=id;keys=new Set();ready=false;promise=null;publish();}if(!id||ready||promise)return promise;const requested=id;promise=(async()=>{const r=await client.from('saved_places').select('listing_id,menu_item_id').eq('profile_id',id);if(owner!==requested)return;if(r.error){promise=null;throw r.error;}keys=new Set((r.data??[]).map(x=>x.listing_id?'l:'+x.listing_id:'m:'+x.menu_item_id));ready=true;publish();})();return promise;}
export function useFavorites(){const identity=useIdentity();const [error,setError]=useState('');const saved=useSyncExternalStore(fn=>{subscribers.add(fn);return()=>{subscribers.delete(fn);};},()=>snapshot);useEffect(()=>{setError('');void load(identity.role==='traveler'?identity.id:null)?.catch(e=>setError(errorMessage(e)));},[identity.id,identity.role]);return {saved,error,ready,retry:()=>{setError('');promise=null;void load(identity.id)?.catch(e=>setError(errorMessage(e)));}};}
export function SavedHeart({listing,menu,name,floating=true}:{listing?:string;menu?:string;name:string;floating?:boolean}){const identity=useIdentity(),favorites=useFavorites(),[busy,setBusy]=useState(false),[error,setError]=useState('');const item=listing?'l:'+listing:'m:'+menu,selected=favorites.saved.includes(item);if(identity.role==='owner'||identity.role==='admin')return null;async function toggle(){if(identity.role==='guest'){sessionStorage.setItem('travelmate:entry-intent','traveler');navigate('/register/traveler');return;}if(busy||!favorites.ready)return;setBusy(true);setError('');try{const uid=currentIdentity().id;const r=await client.rpc('set_saved_place',{p_listing:listing??null,p_menu:menu??null,p_saved:!selected});if(r.error)throw r.error;if(owner!==uid)return;selected?keys.delete(item):keys.add(item);publish();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
return <span className={floating?'tm-save-position':'tm-save-inline'}><button className="tm-save-heart" type="button" aria-label={(selected?'Remove ':'Save ')+name} aria-pressed={selected} disabled={busy||identity.role==='loading'||identity.role==='traveler'&&!favorites.ready} title={error||favorites.error||(selected?'Saved':'Save for later')} onClick={e=>{e.stopPropagation();void toggle();}}><Heart size={21} fill={selected?'currentColor':'none'}/></button>{(error||favorites.error)&&<small className="tm-save-error" role="alert">{error||favorites.error}<button type="button" onClick={favorites.retry}>Retry</button></small>}</span>;}
export function mountSavedHeart(node:HTMLElement,id:string,name:string){const root=createRoot(node);root.render(<SavedHeart listing={id} name={name}/>);return()=>root.unmount();}
