import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, MapPin, Plus, CalendarDays, Compass, BedDouble, Utensils, Sparkles, Bookmark, Users, Building2, MousePointer2, Ticket, Clock3, Download, RefreshCw } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { client, useIdentity, navigate, errorMessage, money, track, type Destination } from './state';
import { EmptyState, ErrorState, LoadingCards, PageHeading } from './shared';
import { Recommendations } from './recommendations';
import { destinationPhoto } from './destination-photos';
import { DestinationCarousel } from './destination-carousel';
import { DestinationCover, PhotoCredit } from './destination-picture';

type Trip = { id: string; name: string; start_date: string; end_date: string; status: string };
export type Overview = { role: string; users: number; owners: number; listings: number; approved: number; pending: number; rejected: number; page_views: number; active_users: number; listing_views: number; bookings: number; paid_total: number; avg_api_ms: number | null; tracking_since: string | null; daily: { date: string; views: number }[]; businesses: { id: string; name: string; listing_type: string; status: string; views: number; bookings: number }[] };
function createTrip(destination?: string) { if (destination) sessionStorage.setItem('travelmate:plan-destination', destination); navigate('/trips'); window.dispatchEvent(new Event('travelmate:new-trip')); }
const destinationStyles = ['tm-destination-sand', 'tm-destination-forest', 'tm-destination-coast', 'tm-destination-clay'];
export function TravelerHome() {
  const identity = useIdentity(); const [destinations, setDestinations] = useState<Destination[]>([]); const [trips, setTrips] = useState<Trip[]>([]); const [counts, setCounts] = useState({ trips: 0, saved: 0, bookings: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { let cancelled = false; setLoading(true); setError(''); setDestinations([]); setTrips([]);
    void (async () => { try {
      const [d, t, tc, sc, bc] = await Promise.all([client.from('destinations').select('id,name,province,description').eq('is_active', 1).order('name').limit(6), client.from('trips').select('id,name,start_date,end_date,status').eq('profile_id', identity.id!).order('updated_at', { ascending: false }).limit(3), client.from('trips').select('id', { head: true, count: 'exact' }).eq('profile_id', identity.id!), client.from('saved_destinations').select('destination_id', { head: true, count: 'exact' }).eq('profile_id', identity.id!), client.from('bookings').select('id', { head: true, count: 'exact' }).eq('profile_id', identity.id!)]);
      for (const result of [d, t, tc, sc, bc]) if (result.error) throw result.error;
      if (cancelled) return; setDestinations(d.data ?? []); setTrips(t.data ?? []); setCounts({ trips: tc.count ?? 0, saved: sc.count ?? 0, bookings: bc.count ?? 0 });
    } catch (e) { if (!cancelled) setError(errorMessage(e)); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; };
  }, [identity.id, version]);
  return <div className="tm-page tm-traveler-home"><div className="tm-welcome-row"><p className="tm-eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><span><CalendarDays size={14} />{new Intl.DateTimeFormat('en-PH', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'Asia/Taipei' }).format(new Date())}</span></div>
    <div className="tm-traveler-hero"><div className="tm-hero-copy"><span className="tm-pill"><Sparkles size={13} />Made for the way you travel</span><h1>Where will you<br />go next?</h1><p>Hi {identity.name.split(' ')[0] || 'traveler'}. Pick a place, find your favorites, and turn “someday” into a day-by-day plan.</p><div className="tm-hero-actions"><Button size="lg" onClick={() => createTrip()}><Plus />Create an itinerary<ArrowUpRight /></Button><Button variant="ghost" onClick={() => navigate('/explore')}>Explore first<ArrowRight /></Button></div><div className="tm-hero-footnote"><span className="tm-mini-compass"><Compass size={16} /></span>Your destination. Your pace. Your kind of trip.</div></div><div className="travel-home-gallery"><DestinationCarousel name="San Juan" province="La Union"/></div></div>
    <div className="tm-personal-stats">{[{ label: 'Your itineraries', value: counts.trips, icon: Compass, target: '/trips' }, { label: 'Saved destinations', value: counts.saved, icon: Bookmark, target: '/explore' }, { label: 'Bookings & tickets', value: counts.bookings, icon: Ticket, target: '/bookings' }].map(({ label, value, icon: Icon, target }) => <button key={label} onClick={() => navigate(target)}><span className="tm-stat-icon"><Icon size={19} /></span><span><strong>{loading ? '…' : error ? '—' : value}</strong><small>{label}</small></span><ArrowUpRight size={16} /></button>)}</div>
    <form className="tm-destination-search" onSubmit={e => { e.preventDefault(); navigate('/explore'); const input = document.getElementById('search') as HTMLInputElement; input.value = query; document.getElementById('search-form')?.dispatchEvent(new Event('submit', { cancelable: true, bubbles: true })); }}><MapPin size={21} /><div><label htmlFor="tm-home-search">Where are we heading?</label><input id="tm-home-search" type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Try Agoo, San Juan, or La Union" /></div><Button type="submit">Find a destination<ArrowRight /></Button></form>
    {error && <ErrorState message={error} retry={() => setVersion(x => x + 1)} />}
    <Recommendations />
    <div className="tm-section-title"><div><p className="tm-eyebrow">START WITH A PLACE</p><h2>Small towns. Big possibilities.</h2></div><Button variant="ghost" onClick={() => navigate('/explore')}>All destinations<ArrowUpRight /></Button></div>
    {loading ? <LoadingCards /> : <div className="tm-destination-grid">{destinations.slice(0, 4).map((d, i) => {const photo=destinationPhoto(d.name,d.province); return <div className="tm-destination-entry" key={d.id}><button className={'tm-destination-card tm-destination-with-photo ' + destinationStyles[i]} onClick={() => navigate('/destination/' + d.id)}><DestinationCover key={d.id} photo={photo}/><small>{d.province}</small><h3>{d.name}</h3><span className="tm-destination-link">Stays, food & things to do<ArrowUpRight size={17} /></span></button><PhotoCredit photo={photo} compact/></div>;})}</div>}
    <div className="tm-home-bottom"><Card><CardContent className="p-6"><div className="tm-section-title"><h2>Your travel notebook</h2><Button variant="ghost" size="sm" onClick={() => navigate('/trips')}>View all<ArrowUpRight /></Button></div>{trips.length ? trips.map(trip => <a className="tm-trip-row" key={trip.id} href="#/trips"><span className="tm-stat-icon"><CalendarDays size={19} /></span><span><strong>{trip.name}</strong><small>{trip.start_date || 'Dates to come'} · {trip.status}</small></span><ArrowUpRight size={18} /></a>) : <EmptyState title="Your first adventure belongs here" action={<Button variant="outline" onClick={() => createTrip()}>Plan my first itinerary<Plus /></Button>}>A destination and a few dates are all you need to get started.</EmptyState>}</CardContent></Card><Card className="tm-trip-help"><CardContent className="p-6"><p className="tm-eyebrow">MAKE A DAY OF IT</p><h2>Find a stay.<br />Taste something local.<br />Take the long way.</h2><p>Open a destination to find its approved places together, then build your itinerary around them.</p><div className="tm-help-icons"><BedDouble /><Utensils /><Compass /></div><Button variant="outline" onClick={() => navigate('/explore')}>Find my next stop<ArrowRight /></Button></CardContent></Card></div>
  </div>;
}

export function ActivityChart({ data }: { data: Overview['daily'] }) { const max = Math.max(1, ...data.map(x => x.views)); return <div className="tm-chart" role="img" aria-label={'Daily recorded activity: ' + data.map(d => `${d.date}: ${d.views}`).join(', ')}><div className="tm-chart-bars">{data.map(d => <div key={d.date} title={`${d.date}: ${d.views}`}><span style={{ height: `${Math.max(2, d.views / max * 100)}%` }} /><small>{new Date(d.date + 'T12:00:00').getDate()}</small></div>)}</div><div className="tm-chart-caption"><span>{data[0]?.date}</span><span>Last 14 days · recorded activity</span><span>{data.at(-1)?.date}</span></div></div>; }
function downloadReport(data: Overview) {
  const cell = (value: unknown) => '"' + String(value ?? '').replace(/^[=+@-]/, "'$&").replaceAll('"', '""') + '"';
  const rows: unknown[][] = [['TravelMate', data.role + ' report', new Date().toISOString()], ['Activity window', 'Last 30 days'], ['Tracking since', data.tracking_since || 'No events yet'], ['Listing views', data.listing_views], ['Total bookings (all statuses, all time)', data.bookings], ['Paid booking value PHP (all time)', data.paid_total], [], ['Business (first 200)', 'Type', 'Status', 'Views (30 days)', 'Bookings (all time)'], ...data.businesses.map(x => [x.name, x.listing_type, x.status, x.views, x.bookings]), [], ['Date', 'Recorded views'], ...data.daily.map(x => [x.date, x.views])];
  const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(row => row.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8;' })); const a = document.createElement('a'); a.href = url; a.download = `travelmate-${data.role}-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function WorkspaceHome({ report = false }: { report?: boolean }) {
  const identity = useIdentity(); const admin = identity.role === 'admin'; const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState(''); const [version, setVersion] = useState(0); const [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; setData(null); setLoading(true); setError(''); const start = performance.now();
    void client.rpc('workspace_overview').then(({ data: result, error: problem }) => { if (cancelled) return; if (problem) setError(errorMessage(problem)); else { setData(result as Overview); void track('api_timing', 'workspace_overview', performance.now() - start); } setLoading(false); }); return () => { cancelled = true; };
  }, [identity.id, identity.role, version]);
  const metrics = data ? admin ? [{ label: 'Total users', value: data.users, note: 'Registered profiles', icon: Users }, { label: 'Business owners', value: data.owners, note: 'Registered businesses', icon: Building2 }, { label: 'Signed-in page views', value: data.page_views, note: 'Last 30 days', icon: MousePointer2 }, { label: 'Total bookings', value: data.bookings, note: 'All statuses · all time', icon: Ticket }] : [{ label: 'Your live listings', value: data.approved, note: `${data.listings} total listings`, icon: Building2 }, { label: 'Listing views', value: data.listing_views, note: 'Signed-in views · last 30 days', icon: MousePointer2 }, { label: 'Reservations', value: data.bookings, note: 'All statuses · all time', icon: Ticket }, { label: 'Paid booking value', value: money(data.paid_total), note: 'Before refunds · all time', icon: BarChartIcon }] : [];
  return <div className="tm-page"><PageHeading eyebrow={admin ? 'PLATFORM OPERATIONS' : 'YOUR BUSINESS, IN GOOD COMPANY'} title={report ? 'Reports & performance' : admin ? 'A clear view of TravelMate.' : `Welcome back, ${identity.name.split(' ')[0] || 'partner'}.`} description={admin ? 'Monitor platform activity and keep every listing worthy of a traveler’s trust.' : 'Your listings, your guests, and your next opportunity—all in one place.'} action={<div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Refresh overview" onClick={() => setVersion(x => x + 1)}><RefreshCw /></Button>{report ? <Button disabled={!data} onClick={() => data && downloadReport(data)}><Download />Export CSV</Button> : <Button onClick={() => navigate(admin ? '/admin' : '/owner')}>{admin ? 'Review listings' : 'Manage my listings'}<ArrowUpRight /></Button>}</div>} />
    {error ? <ErrorState message={error} retry={() => setVersion(x => x + 1)} /> : loading ? <LoadingCards /> : data && <><div className="tm-metric-grid">{metrics.map(({ label, value, note, icon: Icon }) => <Card key={label}><CardContent className="p-5"><div className="tm-metric-label"><span>{label}</span><Icon size={18} /></div><strong className="tm-metric-value">{value}</strong><small className="tm-muted">{note}</small></CardContent></Card>)}</div><div className="tm-dashboard-grid"><Card><CardContent className="p-6"><div className="tm-section-title"><div><p className="tm-eyebrow">ENGAGEMENT</p><h2>{admin ? 'People exploring the platform' : 'Interest in your listings'}</h2></div><span className="tm-pill">14 days</span></div><ActivityChart data={data.daily} /><p className="tm-data-note">Signed-in activity only. {data.tracking_since ? `Tracking began ${new Date(data.tracking_since).toLocaleDateString('en-PH')}.` : 'Tracking starts with new visits; historical traffic is unavailable.'}</p></CardContent></Card><Card className="tm-action-panel"><CardContent className="p-6"><p className="tm-eyebrow">{admin ? 'CATALOG HEALTH' : 'LISTING HEALTH'}</p><h2>{data.pending ? 'A little attention goes a long way.' : 'Keep good things moving.'}</h2><div className="tm-health-row"><span>Awaiting review</span><strong>{data.pending}</strong></div><div className="tm-health-row"><span>{admin ? 'Approved listings' : 'Your approved listings'}</span><strong>{data.approved}</strong></div><div className="tm-health-row"><span>Needs changes</span><strong>{data.rejected}</strong></div><Button className="w-full" onClick={() => navigate(admin ? '/admin' : '/owner')}>{admin ? 'Open review queue' : 'Open my listings'}<ArrowRight /></Button></CardContent></Card></div>
    {admin && <div className="tm-performance-strip"><Clock3 size={20} /><div><strong>Browser-to-database response</strong><p>{data.avg_api_ms == null ? 'No timing samples yet.' : `${data.avg_api_ms} ms average for dashboard queries over the last 30 days.`} This measures browser request time, including the network.</p></div><span className="tm-pill">Live database connected</span></div>}
    <Card><CardContent className="p-6"><div className="tm-section-title"><div><p className="tm-eyebrow">{admin ? 'BUSINESS DIRECTORY' : 'PERSONALIZED BUSINESS PERFORMANCE'}</p><h2>{admin ? 'Listings at a glance' : 'How your businesses are doing'}</h2></div><Button variant="ghost" onClick={() => navigate(admin ? '/admin' : '/owner')}>Manage<ArrowUpRight /></Button></div>{data.businesses.length ? <div className="tm-table-scroll"><table className="tm-table"><thead><tr><th>Business</th><th>Status</th><th>Views · 30 days</th><th>Bookings · all time</th></tr></thead><tbody>{data.businesses.map(b => <tr key={b.id}><td><strong>{b.name}</strong><small>{b.listing_type}</small></td><td><span className={'tm-status tm-status-' + b.status}>{b.status === 'approved' ? 'Live' : b.status === 'pending' ? 'Awaiting review' : b.status}</span></td><td>{b.views}</td><td>{b.bookings}</td></tr>)}</tbody></table></div> : <EmptyState title="Your next opportunity starts with a listing" action={!admin && <Button onClick={() => navigate('/owner')}>Add a listing<Plus /></Button>}>Create your first business listing, then submit it for review.</EmptyState>}<p className="tm-data-note">{data.businesses.length === 200 ? 'Showing the latest 200 listings. ' : ''}Views measure opens, not unique visitors. Booking counts include every status. Paid value excludes refund adjustments.</p></CardContent></Card></>}
  </div>;
}
function BarChartIcon(props: { size?: number }) { return <Building2 {...props} />; }
export function Home() { const identity = useIdentity(); return identity.role === 'traveler' ? <TravelerHome key={identity.id} /> : identity.role === 'owner' || identity.role === 'admin' ? <WorkspaceHome key={identity.id} /> : <div className="tm-page" role="status">Loading your workspace…</div>; }
