import { useEffect, useState } from 'react';
import { ArrowUpRight, MapPin, Compass, BedDouble, Utensils, Check, CalendarDays, Building2, MousePointer2, ClipboardCheck } from 'lucide-react';
import { Button } from '../components/ui/button';
import { client, navigate, errorMessage, type Destination } from './state';
import { ErrorState } from './shared';
import { destinationPhoto } from './destination-photos';
import { DestinationCover, PhotoCredit } from './destination-picture';
export const beachPhoto = 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/San_Juan_Beach%2C_La_Union%2C_Jan_2024_%282%29.jpg/1280px-San_Juan_Beach%2C_La_Union%2C_Jan_2024_%282%29.jpg';
export function startPlanning() { sessionStorage.setItem('travelmate:entry-intent', 'traveler'); navigate('/register/traveler'); }
export function joinBusiness() { sessionStorage.setItem('travelmate:entry-intent', 'business_owner'); navigate('/register/business'); }
export function landingSection(id: string) {
  const scroll = () => requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' }));
  if ((location.hash.slice(1) || '/') === '/') scroll();
  else { window.addEventListener('hashchange', scroll, { once: true }); navigate('/'); }
}
type Place = Destination & { count: number };
export function Landing() {
  const [places, setPlaces] = useState<Place[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [version, setVersion] = useState(0);
  useEffect(() => { let cancelled = false; setLoading(true); setError(''); void (async () => { try {
    if (!client) throw new Error('Destination browsing is temporarily unavailable. Please try again.');
    const [d, l] = await Promise.all([client.from('destinations').select('id,name,province,description').eq('is_active', 1).order('name'), client.from('business_listings').select('destination_id').eq('status', 'approved')]);
    if (d.error) throw d.error; if (l.error) throw l.error;
    const counts = new Map<string, number>(); for (const row of l.data ?? []) counts.set(row.destination_id, (counts.get(row.destination_id) || 0) + 1);
    if (!cancelled) setPlaces((d.data ?? []).map(d => ({ ...d, count: counts.get(d.id) || 0 })).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name)));
  } catch (e) { if (!cancelled) setError(errorMessage(e)); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [version]);
  const filtered = places.filter(d => `${d.name} ${d.province}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="tm-landing">
    <section className="lp-hero lp-container" aria-labelledby="lp-title"><div className="lp-hero-copy"><p className="tm-eyebrow"><span className="lp-small-line" />LOCAL PLACES. PERSONAL JOURNEYS.</p><h1 id="lp-title">Less searching.<br />More <em>exploring.</em></h1><p className="lp-lead">The little food stops. The scenic detours. The stay that feels just right. Bring them together in an itinerary made for you.</p><div className="lp-actions"><Button size="lg" onClick={startPlanning}>Create an itinerary<ArrowUpRight /></Button><button className="lp-text-link" onClick={() => landingSection('lp-destinations')}>Explore destinations<span aria-hidden="true">↗</span></button></div><p className="lp-reassurance"><Check size={14} />Explore first. Create an account when you’re ready to plan.</p><div className="lp-hero-meta"><span><Compass />Find your place</span><span><CalendarDays />Make it your own</span></div></div>
    <div className="lp-hero-visual"><div className="lp-photo"><img src={beachPhoto} alt="Waves and sandy shoreline at San Juan Beach, La Union" fetchPriority="high" onError={e => { e.currentTarget.hidden = true; }} /><span className="lp-photo-location"><MapPin size={13} />SAN JUAN, LA UNION</span><span className="lp-photo-note">A little closer to your next escape.</span></div><div className="lp-route-card"><div className="lp-route-top"><span><Compass size={15} />YOUR KIND OF DAY</span><span>EXAMPLE PLAN</span></div><h2>A day with room<br />to wander.</h2><div className="lp-route-stops"><p><span>09:00</span><Compass size={15} /><strong>A little local exploring</strong></p><p><span>12:30</span><Utensils size={15} /><strong>Lunch worth slowing down for</strong></p><p><span>16:00</span><BedDouble size={15} /><strong>Check in. Switch off.</strong></p></div><div className="lp-route-bottom"><span>YOUR DESTINATION · YOUR PACE</span><ArrowUpRight size={19} /></div></div><span className="lp-visual-note">LESS PLANNING. MORE POSSIBILITY.</span></div></section>
    <div className="lp-value-strip"><div className="lp-container"><span><BedDouble />Somewhere to stay</span><span><Utensils />Something local to taste</span><span><Compass />A reason to take the long way</span></div></div>
    <section id="lp-destinations" className="lp-container lp-section"><div className="lp-section-heading"><div><p className="tm-eyebrow">START WITH A PLACE</p><h2>Where will your<br /><em>next story begin?</em></h2></div><p>Discover La Union, Baguio, and the local places in our growing catalog. Open a destination to find stays, food, and things to do together.</p></div><label className="lp-search"><MapPin size={18} /><span className="sr-only">Search destinations</span><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a town or province…" /></label>
    {error && <ErrorState message={error} retry={() => setVersion(v => v + 1)} />}{loading && <p role="status" className="tm-muted">Finding your next stop…</p>}<div className="lp-destination-grid">{filtered.slice(0, query ? 30 : 4).map((d, i) => <div className="tm-destination-entry" key={d.id}><button className={'lp-destination lp-destination-' + i % 4} onClick={() => navigate('/destination/' + d.id)}><DestinationCover photo={destinationPhoto(d.name,d.province)}/><div className="lp-destination-copy"><p>{d.province.replace(' (geographic location)', '')}</p><h3>{d.name}<ArrowUpRight size={22} /></h3><span>{d.count ? `${d.count} approved local ${d.count === 1 ? 'place' : 'places'}` : 'Explore the destination'}</span></div></button><PhotoCredit photo={destinationPhoto(d.name,d.province)}/></div>)}</div>{!loading && !error && !filtered.length && <p className="tm-muted">No destinations match that search. Try another town or province.</p>}</section>
    <section id="lp-how" className="lp-how"><div className="lp-container"><div className="lp-section-heading"><div><p className="tm-eyebrow">FROM “LET’S GO” TO A PLAN</p><h2>A good trip starts<br />with a <em>little direction.</em></h2></div><p>You choose the destination and the pace. TravelMate helps bring the details into one place.</p></div><div className="lp-steps">{[{ n: '01', icon: MapPin, title: 'Pick your starting point', copy: 'Explore a destination and get to know the places around it.' }, { n: '02', icon: CalendarDays, title: 'Tell us your kind of trip', copy: 'Add your dates, budget, interests, and who’s coming along.' }, { n: '03', icon: Compass, title: 'Make the days your own', copy: 'Create a day-by-day itinerary, adjust it, and reserve available stays or tables.' }].map(({ n, icon: Icon, title, copy }) => <div key={n}><div className="lp-step-top"><Icon size={25} strokeWidth={1.3} /><span>{n}</span></div><h3>{title}</h3><p>{copy}</p></div>)}</div><p className="lp-footnote">An itinerary is your plan. Reservations are confirmed separately, subject to availability.</p></div></section>
    <section id="lp-business" className="lp-container lp-section"><div className="lp-owner"><div className="lp-owner-copy"><p className="tm-eyebrow">FOR THE PEOPLE BEHIND THE PLACES</p><h2>Put your business<br />on their <em>next itinerary.</em></h2><p>Run a hotel, restaurant, or attraction? Give travelers a reason to stop by—and a place to discover what makes your business special.</p><ul><li><Building2 />Showcase your places, photos, and details</li><li><ClipboardCheck />Manage hotel and restaurant reservations</li><li><MousePointer2 />See listing views and booking performance</li></ul><Button size="lg" onClick={joinBusiness}>List your business<ArrowUpRight /></Button><p className="lp-footnote">Create an owner account. Submit your listing. Go live after administrator approval.</p></div><div className="lp-owner-preview" aria-label="Illustrative business portal preview"><div className="lp-preview-header"><span><Building2 size={18} />YOUR BUSINESS PORTAL</span><span className="lp-preview-dot" /></div><p className="lp-preview-eyebrow">YOUR BUSINESS, IN GOOD COMPANY</p><h3>A place for your<br />next chapter.</h3><div className="lp-preview-metrics"><div><MousePointer2 size={17} /><strong>Listing views</strong><span>Understand your reach</span></div><div><ClipboardCheck size={17} /><strong>Reservations</strong><span>Keep guests in view</span></div></div><div className="lp-preview-listing"><span className="lp-preview-icon"><BedDouble size={27} /></span><div><strong>Your local business</strong><span>Photos · Details · Availability</span></div><Check size={18} /></div><div className="lp-preview-chart" aria-hidden="true">{[25, 40, 33, 60, 47, 65, 55, 78, 68, 90].map((h, i) => <span key={i} style={{ height: h + '%' }} />)}</div><p className="lp-footnote">Illustrative preview · your dashboard uses your own business data.</p></div></div></section>
    <section className="lp-closing lp-container"><Compass size={32} strokeWidth={1.1} /><p>Good places. Thoughtful plans.<br /><strong>A little more to look forward to.</strong></p><span>U-MATTER · TRAVELMATE</span></section>
    <div className="lp-photo-credit">San Juan Beach photo by <a href="https://commons.wikimedia.org/wiki/File:San_Juan_Beach,_La_Union,_Jan_2024_(2).jpg" target="_blank" rel="noreferrer">Ralff Nestor Nacor</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a> · displayed cropped.</div>
  </div>;
}
