import {useEffect,useId,useRef,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import {X} from 'lucide-react';
import {Button} from '../components/ui/button';
export function Modal({title,children,close,className='',closeOnOutside=false,exiting=false,onExitComplete}:{title:string;children:ReactNode;close:()=>void;className?:string;closeOnOutside?:boolean;exiting?:boolean;onExitComplete?:()=>void}){
 const id=useId(),ref=useRef<HTMLElement>(null),closer=useRef(close);closer.current=close;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;const siblings=Array.from(document.body.children).filter(n=>n!==ref.current?.parentElement) as HTMLElement[];const wasInert=siblings.map(n=>n.inert);siblings.forEach(n=>n.inert=true);document.body.style.overflow='hidden';ref.current?.focus();const focus=()=>{if(!document.querySelector('.tm-shadcn-confirm')&&!ref.current?.contains(document.activeElement))ref.current?.focus();};const key=(e:KeyboardEvent)=>{if(document.querySelector('.tm-shadcn-confirm'))return;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closer.current();}if(e.key!=='Tab')return;const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]')??[]).filter(n=>n.getClientRects().length);if(!nodes.length){e.preventDefault();ref.current?.focus();return;}const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}};const observer=new MutationObserver(focus);if(ref.current)observer.observe(ref.current,{childList:true,subtree:true});document.addEventListener('focusin',focus);document.addEventListener('keydown',key,true);return()=>{observer.disconnect();document.removeEventListener('focusin',focus);document.removeEventListener('keydown',key,true);document.body.style.overflow=overflow;siblings.forEach((n,i)=>n.inert=wasInert[i]);if(previous?.isConnected)previous.focus();};},[]);
 return createPortal(<div className={'tm-react tm-modal-backdrop '+className+(exiting?' tm-modal-exiting':'')} onPointerDown={e=>{if(closeOnOutside&&e.target===e.currentTarget&&!document.querySelector('.tm-shadcn-confirm'))close();}}><section ref={ref} inert={exiting} onAnimationEnd={e=>{if(exiting&&e.target===e.currentTarget&&e.animationName==='tm-drawer-out')onExitComplete?.();}} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={id} className="tm-modal"><header className="tm-modal-header"><h2 id={id}>{title}</h2><Button variant="ghost" size="icon" aria-label="Close window" disabled={exiting} onClick={close}><X/></Button></header>{children}</section></div>,document.body);
}
