import { useEffect, useState } from 'react';
import { Compass, Map, LayoutDashboard, BedDouble, Utensils, MapPin, Building2, BarChart3, Ticket, ClipboardCheck, UserRound, LogOut, Menu, X, ArrowUpRight, ShieldCheck, Plus } from 'lucide-react';
import { Button } from '../components/ui/button';
import { useIdentity, navigate } from './state';
const travelerLinks = [{ path: '/home', label: 'Overview', icon: LayoutDashboard }, { path: '/trips', label: 'My itineraries', icon: Map }, { path: '/explore', label: 'Destinations', icon: Compass }, { path: '/stay', label: 'Places to stay', icon: BedDouble }, { path: '/eat', label: 'Places to eat', icon: Utensils }, { path: '/attractions', label: 'Things to do', icon: MapPin }, { path: '/bookings', label: 'Bookings & tickets', icon: Ticket }];
const ownerLinks = [{ path: '/home', label: 'Business overview', icon: LayoutDashboard }, { path: '/owner', label: 'My listings', icon: Building2 }, { path: '/reservations', label: 'Reservations', icon: Ticket }, { path: '/reports', label: 'Performance report', icon: BarChart3 }];
const adminLinks = [{ path: '/home', label: 'Platform overview', icon: LayoutDashboard }, { path: '/admin', label: 'Listing reviews', icon: ClipboardCheck }, { path: '/reports', label: 'Reports & analytics', icon: BarChart3 }];
export function Navigation() {
  const identity = useIdentity(); const [path, setPath] = useState(location.hash.slice(1) || '/'); const [open, setOpen] = useState(false);
  useEffect(() => { const change = () => { setPath(location.hash.slice(1) || '/'); setOpen(false); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => { setOpen(false); }, [identity.role]);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const isGuest = identity.role === 'guest';
  const links = identity.role === 'owner' ? ownerLinks : identity.role === 'admin' ? adminLinks : identity.role === 'traveler' ? travelerLinks : [];
  const roleLabel = identity.role === 'owner' ? 'Business portal' : identity.role === 'admin' ? 'Admin console' : identity.role === 'loading' ? 'Loading workspace' : 'Traveler workspace';
  const logo = <><span className="tm-logo-mark"><Compass size={23} /></span><span>Travel<span className="tm-logo-light">Mate</span><small>{isGuest ? 'A little local. A lot of possibility.' : roleLabel}</small></span></>;
  if (isGuest) return <div className="tm-guest-navigation"><a className="tm-logo" href="#/">{logo}</a><nav aria-label="Guest navigation"><a href="#/login">Log in</a><Button asChild><a href="#/register">Start your journey<ArrowUpRight /></a></Button></nav></div>;
  return <><a href="#main-content" className="tm-skip">Skip to content</a><div className="tm-topbar"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="tm-mobile-toggle" onClick={() => setOpen(!open)} aria-controls="tm-sidebar" aria-expanded={open} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X /> : <Menu />}</Button><span className="tm-topbar-workspace">{identity.role === 'admin' ? <ShieldCheck size={16} /> : identity.role === 'owner' ? <Building2 size={16} /> : <Compass size={16} />}{roleLabel}</span></div><div className="flex items-center gap-3"><span className="tm-topbar-name">{identity.name || 'Welcome'}</span><a className="tm-avatar" href="#/account" aria-label="My account">{identity.name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'TM'}</a></div></div>{open && <button className="tm-sidebar-overlay" aria-label="Close navigation" onClick={() => setOpen(false)} />}<aside id="tm-sidebar" className={'tm-sidebar' + (open ? ' tm-sidebar-open' : '')}><a className="tm-logo" href="#/home">{logo}</a>{identity.role === 'traveler' && <Button className="tm-create-button" onClick={() => { navigate('/trips'); window.dispatchEvent(new Event('travelmate:new-trip')); setOpen(false); }}><Plus />Create an itinerary</Button>}<p className="tm-nav-label">{identity.role === 'traveler' ? 'YOUR NEXT ADVENTURE' : 'YOUR WORKSPACE'}</p><nav aria-label={roleLabel}>{links.map(({ path: target, label, icon: Icon }) => <a key={target} href={'#' + target} className={path === target ? 'tm-nav-link active' : 'tm-nav-link'} aria-current={path === target ? 'page' : undefined}><Icon size={19} /><span>{label}</span>{path === target && <span className="tm-nav-dot" />}</a>)}</nav><div className="tm-sidebar-bottom"><div className="tm-workspace-note"><ShieldCheck size={17} /><p>{identity.role === 'traveler' ? 'Local places. Thoughtful plans.' : identity.role === 'owner' ? 'Your business, in good company.' : 'A trusted catalog starts here.'}<small>{identity.role === 'traveler' ? 'Explore approved local listings.' : identity.role === 'owner' ? 'Only your listings and reservations.' : 'Review. Monitor. Improve.'}</small></p></div><a href="#/account" className="tm-nav-link"><UserRound size={19} />Account settings</a><button className="tm-nav-link" onClick={() => document.getElementById('logout')?.click()}><LogOut size={19} />Sign out</button><p className="tm-sidebar-footer">U-MATTER · TRAVELMATE</p></div></aside></>;
}
