import { useEffect, useState } from 'react';
import { Heart, Compass, Map, LayoutDashboard, BedDouble, Utensils, MapPin, Building2, BarChart3, Ticket, ClipboardCheck, UserRound, LogOut, Menu, X, ArrowUpRight, ShieldCheck, Plus } from 'lucide-react';
import { Button } from '../components/ui/button';
import { landingSection } from './landing';
import { client, useIdentity, navigate } from './state';
const travelerLinks = [{ path: '/home', label: 'Overview', icon: LayoutDashboard }, { path: '/trips', label: 'My itineraries', icon: Map }, { path: '/explore', label: 'Destinations', icon: Compass }, { path: '/stay', label: 'Places to stay', icon: BedDouble }, { path: '/eat', label: 'Places to eat', icon: Utensils }, { path: '/attractions', label: 'Things to do', icon: MapPin }, {path:'/saved',label:'Saved places',icon:Heart},{ path: '/bookings', label: 'Bookings & tickets', icon: Ticket }];
const ownerLinks = [{ path: '/home', label: 'Business overview', icon: LayoutDashboard }, { path: '/owner', label: 'My listings', icon: Building2 }, { path: '/reservations', label: 'Reservations', icon: Ticket }, { path: '/reports', label: 'Performance report', icon: BarChart3 }];
const adminLinks = [{ path: '/home', label: 'Platform overview', icon: LayoutDashboard }, { path: '/admin', label: 'Listing reviews', icon: ClipboardCheck }, { path: '/reports', label: 'Reports & analytics', icon: BarChart3 }];
export function Navigation() {
  const identity = useIdentity();const [avatar,setAvatar]=useState('');useEffect(()=>{let live=true;setAvatar('');if(identity.id&&identity.role!=='loading')void Promise.resolve(client.from('profiles').select('sample_avatar_url').eq('id',identity.id).maybeSingle()).then(r=>{const url=r.data?.sample_avatar_url;if(live&&!r.error&&typeof url==='string'&&/^\/avatars\/traveler-[1-6]\.svg$/.test(url))setAvatar(url);}).catch(()=>{});return()=>{live=false;};},[identity.id,identity.role]); const [path, setPath] = useState(location.hash.slice(1) || '/'); const [open, setOpen] = useState(false);
  useEffect(() => { const change = () => { setPath(location.hash.slice(1) || '/'); setOpen(false); }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change); }, []);
  useEffect(() => { setOpen(false); }, [identity.role]);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const isGuest = identity.role === 'guest';
  const links = identity.role === 'owner' ? ownerLinks : identity.role === 'admin' ? adminLinks : identity.role === 'traveler' ? travelerLinks : [];
  const roleLabel = identity.role === 'owner' ? 'Business portal' : identity.role === 'admin' ? 'Admin console' : identity.role === 'loading' ? 'Loading workspace' : 'Traveler workspace';
  const logo = <><span className="tm-logo-mark"><Compass size={23} /></span><span>Travel<span className="tm-logo-light">Mate</span><small>{isGuest ? 'A little local. A lot of possibility.' : roleLabel}</small></span></>;
  if (isGuest) return <div className="tm-guest-navigation"><a className="tm-logo" href="#/">{logo}</a><nav aria-label="Guest navigation"><button className="lp-nav-link" onClick={() => landingSection('lp-destinations')}>Destinations</button><button className="lp-nav-link lp-nav-how" onClick={() => landingSection('lp-how')}>How it works</button><button className="lp-nav-link" onClick={() => landingSection('lp-business')}>For businesses</button><a className="lp-nav-login" href="#/login">Log in<ArrowUpRight size={14} /></a></nav></div>;
  return <><a href="#main-content" className="tm-skip">Skip to content</a><div className="tm-topbar"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="tm-mobile-toggle" onClick={() => setOpen(!open)} aria-controls="tm-sidebar" aria-expanded={open} aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X /> : <Menu />}</Button><span className="tm-topbar-workspace">{identity.role === 'admin' ? <ShieldCheck size={16} /> : identity.role === 'owner' ? <Building2 size={16} /> : <Compass size={16} />}{roleLabel}</span></div><div className="flex items-center gap-3"><span className="tm-topbar-name">{identity.name || 'Welcome'}</span><a className="tm-avatar" href="#/account" aria-label="My account">{avatar?<img src={avatar} alt=""/>:identity.name.split(/\s+/).filter(Boolean).slice(0, 2).map(x => x[0]).join('').toUpperCase() || 'TM'}</a></div></div>{open && <button className="tm-sidebar-overlay" aria-label="Close navigation" onClick={() => setOpen(false)} />}<button className="tm-menu-edge" aria-label="Open navigation from edge" onMouseEnter={()=>setOpen(true)} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)}><Menu size={17}/></button><aside id="tm-sidebar" inert={!open} onMouseEnter={()=>{if(matchMedia("(min-width: 761px) and (hover: hover)").matches)setOpen(true);}} onMouseLeave={e=>{if(matchMedia("(min-width: 761px) and (hover: hover)").matches&&!e.currentTarget.contains(document.activeElement))setOpen(false);}} className={'tm-sidebar' + (open ? ' tm-sidebar-open' : '')}><Button className="tm-sidebar-close" variant="ghost" size="icon" aria-label="Close sidebar" onClick={()=>setOpen(false)}><X size={18}/></Button><a className="tm-logo" href="#/home">{logo}</a>{identity.role === 'traveler' && <Button className="tm-create-button" onClick={() => { navigate('/trips'); window.dispatchEvent(new Event('travelmate:new-trip')); setOpen(false); }}><Plus />Create an itinerary</Button>}<p className="tm-nav-label">{identity.role === 'traveler' ? 'YOUR NEXT ADVENTURE' : 'YOUR WORKSPACE'}</p><nav aria-label={roleLabel}>{links.map(({ path: target, label, icon: Icon }) => <a key={target} href={'#' + target} className={path === target ? 'tm-nav-link active' : 'tm-nav-link'} aria-current={path === target ? 'page' : undefined}><Icon size={19} /><span>{label}</span>{path === target && <span className="tm-nav-dot" />}</a>)}</nav><div className="tm-sidebar-bottom"><a href="#/account" className="tm-nav-link"><UserRound size={19} />Account settings</a><button className="tm-nav-link" onClick={() => window.dispatchEvent(new Event('travelmate:sign-out'))}><LogOut size={19} />Sign out</button><p className="tm-sidebar-footer">U-MATTER · TRAVELMATE</p></div></aside></>;
}
