import { useEffect, useState } from 'react';
import { Waves, Mountain, Trees, Utensils, Landmark, Footprints, Coffee, ShoppingBag, Check, ArrowUpRight, Compass } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { client, useIdentity, currentIdentity, navigate, errorMessage } from './state';
import { confirmAction } from '../action-confirm';
const interests = [{ value:'beaches',name:'Beaches',copy:'Salt air & slow sunsets',icon:Waves },{value:'mountains',name:'Mountains',copy:'Cool air & higher views',icon:Mountain},{value:'nature',name:'Nature',copy:'Green spaces & quiet trails',icon:Trees},{value:'food',name:'Food & local culture',copy:'A taste of somewhere new',icon:Utensils},{value:'history',name:'History & heritage',copy:'Places with a story',icon:Landmark},{value:'adventure',name:'Adventure',copy:'A little out of the ordinary',icon:Footprints},{value:'relaxation',name:'Relaxation',copy:'Less rush, more breathing room',icon:Coffee},{value:'shopping',name:'Shopping',copy:'Local finds & little treasures',icon:ShoppingBag}];
export function Preferences() {
 const identity=useIdentity(); const [selected,setSelected]=useState<string[]>([]); const [pace,setPace]=useState('balanced'); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [version,setVersion]=useState(0);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');void client.from('traveler_settings').select('interests,travel_pace').eq('profile_id',identity.id!).maybeSingle().then(r=>{if(cancelled)return;if(r.error)setError(errorMessage(r.error));else{setSelected(r.data?.interests??[]);setPace(r.data?.travel_pace??'balanced');}setLoading(false);});return()=>{cancelled=true;};},[identity.id,version]);
 async function save(skip=false) { const uid=identity.id;setBusy(true);setError('');try {
  const summary=skip?'You can choose interests later from your account. Your existing preferences will be kept.':`${selected.length?selected.map(x=>interests.find(i=>i.value===x)?.name).join(', '):'No specific interests'}\n${pace} pace\nThese are defaults; you can change them for each trip.`;
  if(!await confirmAction(skip?'Explore without personalization?':'Save your travel preferences?',summary,skip?'Skip & explore':'Save & see recommendations')||currentIdentity().id!==uid)return;
  const r=await client.rpc('save_my_travel_preferences',{p_interests:selected,p_pace:pace,p_skip:skip});if(r.error)throw r.error;
  if(currentIdentity().id!==uid)return;
  if(!skip)window.dispatchEvent(new CustomEvent('travelmate:preferences',{detail:{profile_id:uid,interests:selected,travel_pace:pace}}));
  navigate('/home');
 }catch(e){setError(errorMessage(e));}finally{setBusy(false);} }
 return <div className="tm-page tm-preferences"><div className="tm-onboarding-steps" aria-label="Traveler setup progress"><span><Check size={14}/>Account created</span><strong>02 · Your travel style</strong><span>03 · Your recommendations</span></div><div className="tm-preferences-layout"><div><p className="tm-eyebrow">A LITTLE ABOUT YOUR KIND OF GETAWAY</p><h1>What makes you<br /><em>want to go?</em></h1><p className="tm-description">Choose what catches your eye. We’ll use these as the starting point for your itineraries—you can change them any time.</p><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={loading||busy}><legend>Choose your interests · select as many as you like</legend><div className="tm-interest-grid">{interests.map(({value,name,copy,icon:Icon})=><label key={value} className={'tm-interest-option'+(selected.includes(value)?' selected':'')}><input type="checkbox" value={value} checked={selected.includes(value)} onChange={e=>setSelected(s=>e.target.checked?[...s,value]:s.filter(x=>x!==value))}/><Icon size={25} strokeWidth={1.4}/><strong>{name}</strong><small>{copy}</small></label>)}</div><div className="tm-pace-choice"><p>How do you like to spend your days?</p>{[{value:'relaxed',name:'Take it slow',copy:'More breathing room between stops'},{value:'balanced',name:'A bit of both',copy:'A mix of exploring and downtime'},{value:'active',name:'Make the most of it',copy:'More activities in each day'}].map(x=><label key={x.value}><input type="radio" name="pace" value={x.value} checked={pace===x.value} onChange={()=>setPace(x.value)}/><span><strong>{x.name}</strong><small>{x.copy}</small></span></label>)}</div><div className="tm-preference-actions"><Button type="submit">{busy?'Saving…':'Save & see recommendations'}<ArrowUpRight/></Button><Button type="button" variant="ghost" onClick={()=>void save(true)}>Skip for now</Button></div></fieldset></form>{loading&&<p role="status" className="tm-muted">Loading your travel style…</p>}{error&&<div role="alert" className="tm-error"><p>{error}</p><Button variant="outline" onClick={()=>setVersion(v=>v+1)}>Try again</Button></div>}</div><Card className="tm-preference-note"><CardContent className="p-6"><Compass size={38} strokeWidth={1}/><p className="tm-eyebrow">YOUR DESTINATION. YOUR PACE.</p><h2>A trip that feels<br />a little more like you.</h2><p>Your dates, destination, budget, and companions come next.</p><div><Trees size={65} strokeWidth={.8}/><Mountain size={85} strokeWidth={.7}/></div><small>Preferences guide planning. They don’t make reservations or limit the places you can explore.</small></CardContent></Card></div></div>;
}
