import {useEffect,useState} from 'react';
import {Ticket,CalendarDays,Users,BedDouble,Download,ArrowUpRight,XCircle} from 'lucide-react';
import {Button} from '../components/ui/button';
import {Card,CardContent} from '../components/ui/card';
import {confirmAction} from '../action-confirm';
import {client,useIdentity,currentIdentity,navigate,money,errorMessage} from './state';
import {ErrorState,LoadingCards} from './shared';
type Preview={id:string;listing_id:string;listing_name:string;booking_type:string;room_label:string|null;starts_at:string;ends_at:string|null;guest_count:number;guest_name:string;total_amount:number;status:string};
function date(value:string){return new Date(value.length===10?value+'T12:00:00':value).toLocaleString('en-PH',{month:'short',day:'numeric',year:'numeric',...(value.length===10?{}:{hour:'numeric',minute:'2-digit'})});}
function download(b:Preview){const text=['TRAVELMATE · PREVIEW RESERVATION',b.listing_name,'Reference: '+b.id,'Status: '+b.status,'Guest: '+b.guest_name,'Guests: '+b.guest_count,'Arrival: '+date(b.starts_at),'Departure: '+(b.ends_at?date(b.ends_at):'Not applicable'),b.room_label||'Table reservation','Estimated price: '+money(b.total_amount),'','Preview ticket only. No payment was taken and no real inventory is reserved.'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='TravelMate-preview-'+b.id.slice(0,8)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PreviewReservations({version}:{version:number}){
 const identity=useIdentity(),[rows,setRows]=useState<Preview[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState<string|null>(null),[filter,setFilter]=useState('all');
 useEffect(()=>{let cancelled=false;setRows([]);setLoading(true);setError('');void client.from('sample_reservations').select('id,listing_id,listing_name,booking_type,room_label,starts_at,ends_at,guest_count,guest_name,total_amount,status').eq('profile_id',identity.id!).order('created_at',{ascending:false}).limit(200).then(result=>{if(cancelled)return;if(result.error)setError(errorMessage(result.error));else setRows(result.data??[]);setLoading(false);});return()=>{cancelled=true;};},[identity.id,version,revision]);
 async function cancel(b:Preview){if(busy)return;const uid=identity.id;setBusy(b.id);setError('');try{if(!await confirmAction('Cancel this preview reservation?',b.listing_name+'\nYour ticket will stay in your history as cancelled.','Cancel reservation','Keep reservation')||currentIdentity().id!==uid)return;const r=await client.from('sample_reservations').update({status:'cancelled'}).eq('id',b.id).eq('profile_id',uid!).eq('status','reserved').select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('This reservation is already cancelled or unavailable.');if(currentIdentity().id===uid)setRevision(x=>x+1);}catch(e){if(currentIdentity().id===uid)setError(errorMessage(e));}finally{setBusy(null);}}
 if(!loading&&!error&&!rows.length)return null;
 return <section className="tm-preview-reservations" aria-label="Saved preview reservations"><div className="tm-section-title"><div><h2><Ticket/>Earlier preview tickets</h2><p className="tm-muted">Saved tickets · no charge or real inventory hold</p></div><label>Show<select aria-label="Filter preview reservations" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All tickets</option><option value="reserved">Reserved</option><option value="cancelled">Cancelled</option></select></label></div>{error&&<ErrorState message={error} retry={()=>setRevision(x=>x+1)}/>} {loading?<LoadingCards/>:<div className="tm-ticket-grid">{rows.filter(b=>filter==='all'||b.status===filter).map(b=><Card className="tm-booking-ticket tm-preview-ticket" key={b.id}><CardContent className="p-6"><div className="tm-ticket-heading"><span className="tm-eyebrow"><Ticket size={16}/>{b.booking_type==='hotel'?'STAY PREVIEW':'TABLE PREVIEW'}</span><span className={'tm-status tm-status-'+(b.status==='reserved'?'confirmed':'cancelled')}>{b.status}</span></div><h2>{b.listing_name}</h2><p className="tm-ticket-reference">REFERENCE · {b.id.slice(0,8).toUpperCase()}</p><div className="tm-ticket-dashes"/><div className="tm-ticket-details"><span><CalendarDays/><strong>{date(b.starts_at)}</strong><small>{b.ends_at?'to '+date(b.ends_at):'Reservation time'}</small></span><span><Users/><strong>{b.guest_count} guests</strong><small>{b.guest_name}</small></span>{b.room_label&&<span><BedDouble/><strong>{b.room_label}</strong></span>}</div><div className="tm-ticket-dashes"/><div className="tm-ticket-price"><strong>{money(b.total_amount)}</strong><span>Estimate · no charge</span></div><div className="tm-ticket-actions"><Button variant="outline" size="sm" onClick={()=>navigate('/listing/'+b.listing_id)}>View place<ArrowUpRight/></Button><Button variant="outline" size="sm" onClick={()=>download(b)}><Download/>Download ticket</Button>{b.status==='reserved'&&<Button variant="ghost" size="sm" disabled={busy!==null} onClick={()=>void cancel(b)}><XCircle/>Cancel reservation</Button>}</div></CardContent></Card>)}{!rows.filter(b=>filter==='all'||b.status===filter).length&&<p className="tm-muted">No {filter==='all'?'saved':filter} preview reservations yet. Reserve a preview stay or table to try the experience.</p>}</div>}</section>;
}
