import {hasInappropriateWords,reviewDeclinedMessage} from '../review-moderation';
import {Modal} from './modal';
import { useEffect, useRef, useState } from 'react';
import { Star, ShieldCheck, MessageSquare, LockKeyhole, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { confirmAction } from '../action-confirm';
import { client, currentIdentity, useIdentity, navigate, errorMessage } from './state';
import { ErrorState } from './shared';
type Review = { id:string; rating:number; text:string|null; author:string; created_at:string; verified:boolean;avatar?:string };
type Feed = { total:number; average:number|null; can_review:boolean; verified_eligible:boolean; kind:string; mine:{rating:number;text:string|null;status:string}|null; items:Review[]; sample_items?:Review[] };
export function PlaceReviews({ destination, listing, name }: { destination?:string; listing?:string; name:string }) {
 const identity=useIdentity(), section=useRef<HTMLElement>(null), mounted=useRef(true);
 const [declined,setDeclined]=useState(false);
 const [feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[version,setVersion]=useState(0),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false),[rating,setRating]=useState(0),[text,setText]=useState('');
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{let cancelled=false;setError('');setFeed(null);void Promise.resolve(client.rpc('place_reviews',{p_destination:destination??null,p_listing:listing??null,p_offset:offset})).then(result=>{
  if(cancelled)return;if(result.error){setError(errorMessage(result.error));return;}const data=result.data as Feed;setFeed(data);setRating(data.mine?.rating??0);setText(data.mine?.text??'');
  if(location.hash.includes('review=1'))section.current?.scrollIntoView({behavior:'smooth',block:'start'});
 }).catch(e=>{if(!cancelled)setError(errorMessage(e));});return()=>{cancelled=true;};},[destination,listing,identity.id,version,offset]);
 async function submit(event:React.FormEvent){event.preventDefault();if(busy||!feed?.can_review)return;setError('');setMessage('');
  if(!rating||text.trim().length<10||text.length>2000){setError('Choose a star rating and write between 10 and 2,000 characters.');return;}
  if(hasInappropriateWords(text)){setDeclined(true);return;}
  const uid=identity.id;setBusy(true);try{
   if(!await confirmAction(feed.mine?'Update your review?':'Publish your review?',`${name}\n${rating} out of 5 stars\n\n${text.trim()}\n\nYour first name and review will be visible to other travelers.`,feed.mine?'Update review':'Publish review','Keep editing')||currentIdentity().id!==uid||!mounted.current)return;
   const result=await client.rpc('save_traveler_review',{p_destination:destination??null,p_listing:listing??null,p_rating:rating,p_text:text.trim()});if(result.error)throw result.error;
   if(mounted.current&&currentIdentity().id===uid){setMessage('Your review is published. Thank you for sharing your experience.');setOffset(0);setVersion(x=>x+1);}
  }catch(e){if(mounted.current&&currentIdentity().id===uid){if(/REVIEW_INAPPROPRIATE_WORDS/.test(errorMessage(e)))setDeclined(true);else setError(errorMessage(e));}}finally{if(mounted.current)setBusy(false);}
 }
 return <section className="tm-reviews" ref={section} aria-label={'Traveler reviews for '+name}><div className="tm-section-title"><h2><MessageSquare size={22}/>Traveler reviews</h2>{feed&&<span className="tm-review-total"><Star size={18}/>{feed.average??'—'} <small>· {feed.total} {feed.total===1?'review':'reviews'}</small></span>}</div><p className="tm-description">Real experiences to help you plan. Verified booking reviews come from completed stays or reservations.</p>
 {error&&<ErrorState message={error} retry={()=>setVersion(x=>x+1)}/>}{message&&<p role="status" className="tm-review-success">{message}</p>}
 {!feed&&!error?<p className="tm-muted" role="status">Loading reviews…</p>:feed&&<div className="tm-review-layout"><div className="tm-review-feed">{feed.items.length?feed.items.map(review=><Card key={review.id}><CardContent className="p-5"><div className="tm-review-meta">{review.avatar&&<img className="tm-review-avatar" src={review.avatar} alt=""/>}<strong>{review.author}</strong><time dateTime={review.created_at}>{new Date(review.created_at).toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'})}</time></div><div className="tm-review-stars" aria-label={review.rating+' out of 5 stars'}>{[1,2,3,4,5].map(n=><Star key={n} size={16} fill={n<=review.rating?'currentColor':'none'}/>)}</div><span className={review.verified?'tm-review-badge verified':'tm-review-badge'}>{review.verified?<><ShieldCheck size={14}/>Verified booking</>:feed.kind==='destination'?'Traveler review':'Unverified review'}</span><ReviewText text={review.text||'This traveler left a rating.'}/></CardContent></Card>):<div className="tm-review-empty"><MessageSquare size={28}/><h3>No reviews yet</h3><p>Share your experience to help the next traveler.</p></div>}
 {feed.total>10&&<div className="tm-review-pagination"><Button variant="outline" size="sm" disabled={offset===0} onClick={()=>setOffset(x=>Math.max(0,x-10))}><ChevronLeft/>Newer</Button><span>{offset+1}–{Math.min(offset+10,feed.total)} of {feed.total}</span><Button variant="outline" size="sm" disabled={offset+10>=feed.total} onClick={()=>setOffset(x=>x+10)}>Older<ChevronRight/></Button></div>}</div>
 <Card className="tm-review-compose"><CardContent className="p-6"><h3>{feed.mine?'Your review':'How was your experience?'}</h3>{identity.role==='guest'?<><p>Sign in as a traveler to share your experience.</p><Button onClick={()=>navigate('/login')}>Sign in to review</Button></>:feed.can_review?<form onSubmit={e=>void submit(e)}><fieldset disabled={busy}><legend>Rate your experience</legend><div className="tm-star-picker" role="group" aria-label="Star rating">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-label={n+' '+(n===1?'star':'stars')} aria-pressed={rating===n} onClick={()=>setRating(n)}><Star size={25} fill={n<=rating?'currentColor':'none'}/></button>)}</div><p className="tm-review-rating-label">{rating?['','Poor','Fair','Good','Very good','Excellent'][rating]:'Choose 1–5 stars'}</p><label htmlFor="tm-review-text">Your experience<textarea id="tm-review-text" value={text} required minLength={10} maxLength={2000} rows={5} placeholder="What did you enjoy? What should other travelers know?" onChange={e=>setText(e.target.value)}/></label><small>{text.length}/2,000 · One review per place. You can update it later.</small><p className="tm-review-disclosure">{feed.verified_eligible?<><ShieldCheck size={15}/>Your review will show a Verified booking badge.</>:'Your first name and review will be public. A booking is not required for this place.'}</p><Button type="submit" disabled={!rating||text.trim().length<10}>{busy?'Saving…':feed.mine?'Review changes':'Review & publish'}</Button></fieldset></form>:<div className="tm-review-locked"><LockKeyhole size={24}/><p>{feed.mine&&feed.mine.status!=='published'?'Your review is under moderation and cannot be edited right now.':identity.role!=='traveler'?'Reviews are available to traveler accounts.':'Reviews unlock after the business marks your paid stay or reservation as completed.'}</p>{identity.role==='traveler'&&<Button variant="outline" onClick={()=>navigate('/bookings')}>View my bookings</Button>}</div>}</CardContent></Card></div>}
 {feed?.sample_items?.length ? <div className="tm-sample-reviews"><h3>Review previews</h3><p>Sample experiences · separate from traveler ratings.</p><div className="tm-sample-review-grid">{feed.sample_items.map(review=><article key={review.id}><div className="tm-review-meta">{review.avatar&&<img className="tm-review-avatar" src={review.avatar} alt=""/>}<strong>{review.author}</strong><span className="tm-review-badge">Example</span></div><div className="tm-review-stars" aria-label={review.rating+' out of 5 stars, example'}>{[1,2,3,4,5].map(n=><Star key={n} size={16} fill={n<=review.rating?'currentColor':'none'}/>)}</div><ReviewText text={review.text?.replace(/^Example experience:\s*/,'')||'A traveler left a rating.'}/></article>)}</div></div>:null}
 {declined&&<Modal title="Review declined" close={()=>setDeclined(false)} closeOnOutside className="tm-review-declined"><div className="tm-declined-content"><ShieldCheck size={38}/><p>{reviewDeclinedMessage}</p><Button onClick={()=>setDeclined(false)}>Edit my review</Button></div></Modal>}
 </section>;
}


export function ReviewText({text}:{text:string}){const [expanded,setExpanded]=useState(false);const long=text.length>260;return <div className="tm-review-excerpt"><p className="tm-review-text">{long&&!expanded?text.slice(0,260).trimEnd()+'…':text}</p>{long&&<button type="button" className="tm-review-more" aria-expanded={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?'Show less':'Show more'}</button>}</div>;}
