import type { ReactNode } from 'react';
import { ArrowUpRight, BedDouble, Compass, Utensils, MapPin, RefreshCw } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { navigate, type Listing } from './state';
export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="tm-page-heading"><div><p className="tm-eyebrow">{eyebrow}</p><h1>{title}</h1><p className="tm-description">{description}</p></div>{action}</div>; }
export function EmptyState({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <div className="tm-empty"><Compass size={30} /><h3>{title}</h3><p>{children}</p>{action}</div>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="tm-error" role="alert"><p>{message}</p><Button variant="outline" onClick={retry}><RefreshCw />Try again</Button></div>; }
export function LoadingCards() { return <div className="tm-card-grid" aria-label="Loading" aria-busy="true">{[1, 2, 3].map(n => <div className="tm-loading-card animate-pulse" key={n}><div /><span /><span /></div>)}</div>; }
const icons = { hotel: BedDouble, restaurant: Utensils, attraction: Compass };
export function ListingCard({ listing, reason, compact = false }: { listing: Listing; reason?: string; compact?: boolean }) { const Icon = icons[listing.listing_type]; return <Card className="tm-place-card overflow-hidden" onClick={e=>{if(!(e.target as HTMLElement).closest("button,a,input,textarea"))navigate("/listing/"+listing.id);}}><div className={'tm-place-cover tm-cover-' + listing.listing_type}>{listing.image ? <img src={listing.image} alt="" loading="lazy" onError={e => { e.currentTarget.hidden = true; }} /> : <Icon size={42} strokeWidth={1.2} />}<span className="tm-cover-badge">{listing.listing_type === 'hotel' ? 'Stay' : listing.listing_type === 'restaurant' ? 'Eat' : 'Explore'}</span></div><CardContent className="p-5"><h3>{listing.name}</h3>{reason && <p className="tm-match-reason">{reason}</p>}<p className="tm-place-address"><MapPin size={13} />{listing.address || 'View location details'}</p>{(!compact || (listing.description?.trim() && listing.description.trim() !== 'Discover this approved local listing.')) && <p className="tm-place-description">{listing.description || 'Discover this approved local listing.'}</p>}<Button variant="outline" className="w-full" onClick={() => navigate('/listing/' + listing.id)}>View {listing.listing_type === 'hotel' ? 'rooms & book' : listing.listing_type === 'restaurant' ? 'menu & reserve' : 'details'}<ArrowUpRight /></Button></CardContent></Card>; }
