import {useEffect,useState} from 'react';
import {Bus,Check,Compass,MapPin,ArrowUpRight} from 'lucide-react';
import {client,useIdentity,errorMessage,navigate} from './state';
import {DestinationCarousel} from './destination-carousel';
import {Button} from '../components/ui/button';
type Selection={id:string;name:string;province:string;disabled:boolean};
function selection():Selection{const form=document.querySelector<HTMLFormElement>('#trip-form'),select=form?.elements.namedItem('destination_id') as HTMLSelectElement|null;const [name,province]=(select?.selectedOptions[0]?.textContent??'').split(' · ');return {id:select?.value??'',name:select?.value?name:'',province:province??'',disabled:document.querySelector<HTMLFieldSetElement>('#trip-fields')?.disabled??true};}
function useTripDestination(){const identity=useIdentity(),[destination,setDestination]=useState(selection);useEffect(()=>{const change=()=>setDestination(selection());const lock=(e:Event)=>setDestination(v=>({...v,disabled:(e as CustomEvent).detail}));window.addEventListener('travelmate:trip-destination',change);window.addEventListener('travelmate:trip-lock',lock);change();return()=>{window.removeEventListener('travelmate:trip-destination',change);window.removeEventListener('travelmate:trip-lock',lock);};},[identity.id,identity.role]);return destination;}
export function TripInspiration(){const d=useTripDestination();return <div className="travel-inspiration">{d.id?<><div className="travel-inspiration-heading"><span className="tm-eyebrow"><MapPin size={14}/>YOUR DESTINATION</span><h2>{d.name}</h2><p>Get a feel for the places you’ll explore.</p></div><DestinationCarousel key={d.id} name={d.name} province={d.province}/><div className="travel-inspiration-footer"><span><Compass size={18}/>Find stays, food & things to do</span><Button variant="ghost" onClick={()=>navigate('/destination/'+d.id)} aria-label={'Explore '+d.name}><ArrowUpRight/></Button></div></>:<><DestinationCarousel name="San Juan" province="La Union"/><div className="travel-inspiration-heading"><h2>Your next adventure starts here</h2><p>Choose a destination to explore its photos and local transport.</p></div></>}</div>;}
type Transport={id:string;name:string;type:string;provider:string;description:string|null};
export function TripTransport(){const d=useTripDestination(),identity=useIdentity(),[options,setOptions]=useState<Transport[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0);
 useEffect(()=>{let live=true;setOptions([]);setSelected('');setError('');if(!d.id||identity.role!=='traveler'){setLoading(false);return;}setLoading(true);void(async()=>{try{const r=await client.rpc('destination_transport_options',{p_destination:d.id});if(r.error)throw r.error;if(live)setOptions(r.data??[]);}catch(e){if(live)setError(errorMessage(e));}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[d.id,identity.id,identity.role,version]);
 useEffect(()=>{const reset=()=>setSelected('');window.addEventListener('travelmate:trip-destination',reset);return()=>window.removeEventListener('travelmate:trip-destination',reset);},[]);
 function choose(t:Transport){const id=selected===t.id?'':t.id;setSelected(id);window.dispatchEvent(new CustomEvent('travelmate:trip-transport',{detail:{destination_id:d.id,id,name:t.name}}));}
 return <section className="travel-form-section travel-transport"><div className="travel-transport-title"><h3><Bus size={19}/>Getting around</h3><span className="tm-pill">Optional</span></div><p className="hint">Choose transport to review in your day planner after saving.</p>{!d.id?<p className="travel-transport-empty"><MapPin size={17}/>Choose a destination to see transport.</p>:loading?<p role="status">Finding transportation…</p>:error?<div role="alert"><p>{error}</p><Button type="button" variant="outline" disabled={d.disabled} onClick={()=>setVersion(v=>v+1)}>Try again</Button></div>:options.length?<div className="travel-transport-options">{options.map(t=><button key={t.id} type="button" disabled={d.disabled} aria-pressed={selected===t.id} onClick={()=>choose(t)}><span className="travel-transport-icon"><Bus size={22}/></span><span><strong>{t.name}</strong><small>{t.provider} · {t.type}</small>{t.description&&<small>{t.description}</small>}</span><span className="travel-transport-check">{selected===t.id?<Check size={17}/>:<span>＋</span>}</span></button>)}</div>:<p className="travel-transport-empty"><Bus size={17}/>No approved transport for this destination yet. You can write your own transport stop in the day planner.</p>}{options.length>0&&<p className="travel-save-hint">Demo services are planning examples. Routes, fares and reservations are not confirmed.</p>}</section>;
}
