import type { SupabaseClient } from '@supabase/supabase-js';
import {buildItinerary,validateSchedule,type Brief,type Stop,type Venue} from './itinerary-engine';
export const itineraryMarkup=`
<dialog id="itinerary-dialog" class="itinerary-dialog"><button type="button" id="itinerary-close">Close</button><p class="eyebrow">YOUR JOURNEY, DAY BY DAY</p><h2 id="itinerary-title"></h2><p id="itinerary-budget"></p><p class="itinerary-disclaimer">Planning proposal, not a booking. Visit durations and transfer allowances are estimates; opening hours, routes and costs are not verified. Your budget is a target, not a quoted total.</p><div class="flex gap-4"><button id="itinerary-generate" class="primary" type="button">Generate preview</button><button id="itinerary-save" type="button" disabled>Save this itinerary</button></div><p id="itinerary-message" role="status" aria-live="polite"></p><div id="itinerary-days"></div></dialog>
<dialog id="itinerary-replace"><form method="dialog"><h2 id="itinerary-confirm-title">Save this schedule?</h2><p id="itinerary-confirm-copy"></p><div class="flex gap-4"><button value="cancel">Go back</button><button id="itinerary-confirm-action" value="save" class="primary">Continue</button></div></form></dialog>
<dialog id="activity-dialog"><p class="eyebrow">MAKE THIS JOURNEY YOURS</p><h2>Edit activity</h2><form id="activity-form"><label>Activity name<input name="activity" required maxlength="255"></label><label>Place<select name="listing_id"><option value="">Personal activity / no linked place</option></select></label><p class="hint">Choose an approved place at this destination, or leave it unlinked for personal plans. Opening hours and routes still need checking.</p><label>Day<input name="planned_date" type="date" required></label><div class="field-pair"><label>Start<input name="planned_time" type="time" required></label><label>End<input name="planned_end_time" type="time" required></label></div><label>My notes<textarea name="notes" maxlength="4000" rows="3"></textarea></label><p id="activity-error" role="alert"></p><div class="flex gap-4"><button type="button" id="activity-cancel">Cancel</button><button type="submit" class="primary">Apply to preview</button></div></form><p class="hint">Applying changes updates the preview. Use Save this itinerary to store it.</p></dialog>`;
const briefColumns='id,name,destination_id,start_date,end_date,arrival_time,departure_time,travel_pace,interests,budget,budget_currency,updated_at,status';
export function initItinerary(client:SupabaseClient){
 const db=client.schema('public');
 const get=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
 const dialog=get<HTMLDialogElement>('itinerary-dialog'),confirm=get<HTMLDialogElement>('itinerary-replace'),editor=get<HTMLDialogElement>('activity-dialog');
 const days=get('itinerary-days'),message=get('itinerary-message'),generate=get<HTMLButtonElement>('itinerary-generate'),save=get<HTMLButtonElement>('itinerary-save'),form=get<HTMLFormElement>('activity-form');
 let epoch=0,brief:(Brief&{status:string})|null=null,preview:Stop[]|null=null,shown:Stop[]=[],busy=false,asking=false,editing=-1;
 const field=(name:string)=>form.elements.namedItem(name) as HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement;
 const say=(s:string,error=false)=>{message.textContent=s;message.classList.toggle('error',error)};
 const controls=()=>{const disabled=busy||asking||!brief||brief.status!=='draft';generate.disabled=disabled;save.disabled=disabled||!preview;days.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=disabled);};
 const text=(e:unknown)=>e&&typeof e==='object'&&'message' in e?String(e.message):String(e);
 const node=(tag:string,value:string,cls='')=>{const n=document.createElement(tag);n.textContent=value;n.className=cls;return n};
 async function ask(title:string,copy:string,action:string){asking=true;controls();get('itinerary-confirm-title').textContent=title;get('itinerary-confirm-copy').textContent=copy;get('itinerary-confirm-action').textContent=action;confirm.returnValue='cancel';confirm.showModal();const result=await new Promise<string>(resolve=>confirm.addEventListener('close',()=>resolve(confirm.returnValue),{once:true}));asking=false;controls();return result==='save';}
 const boundary=(item:Stop)=>item.activity==='Arrive at destination'||item.activity==='Depart destination';
 function render(stops:Stop[]){shown=stops.map(x=>({...x}));days.replaceChildren();if(!stops.length){days.append(node('p','No saved itinerary yet. Generate a preview from the approved catalog.'));return;}let date='',section:HTMLElement;
  stops.forEach((item,index)=>{if(item.planned_date!==date){date=item.planned_date;section=node('section','','itinerary-day');section.append(node('h3',date));days.append(section);}const card=node('article','','itinerary-stop');card.append(node('time',`${item.planned_time.slice(0,5)}–${(item.planned_end_time??item.planned_time).slice(0,5)}`),node('h4',item.activity),node('p',item.recommendation_reason??'Saved itinerary activity.'),node('small',item.notes??''));
   if(brief?.status==='draft'&&!boundary(item)){const edit=document.createElement('button');edit.type='button';edit.textContent='Edit time or place';edit.onclick=()=>void editActivity(index);card.append(edit);}else if(boundary(item))card.append(node('small','Travel boundary. Change the trip brief and regenerate to adjust it.'));section!.append(card);
  });controls();
 }
 function clear(){epoch++;brief=null;preview=null;shown=[];busy=false;editing=-1;days.replaceChildren();say('');get('itinerary-title').textContent='';get('itinerary-budget').textContent='';if(confirm.open)confirm.close('cancel');if(editor.open)editor.close();if(dialog.open)dialog.close();controls();}
 async function open(id:string){clear();const ticket=epoch;dialog.showModal();busy=true;controls();say('Loading your trip…');try{const t=await db.from('trips').select(briefColumns).eq('id',id).single();if(ticket!==epoch)return;if(t.error)throw t.error;brief=t.data as Brief&{status:string};get('itinerary-title').textContent=brief.name;get('itinerary-budget').textContent=`${brief.start_date??'No date'} → ${brief.end_date??'No date'} · Budget target: ${brief.budget_currency??''} ${brief.budget??'Not set'}`;const rows=await db.from('trip_items').select('planned_date,planned_time,planned_end_time,activity,listing_id,recommendation_reason,notes').eq('trip_id',id).order('sequence_number');if(ticket!==epoch)return;if(rows.error)throw rows.error;const scheduled=(rows.data??[]).filter(x=>x.planned_date&&x.planned_time) as Stop[];render(scheduled);say(rows.data?.length!==scheduled.length?'Older items without a date/time are not displayed. Saving replaces them too.':brief.status==='draft'?'Edit an activity or generate a new preview. Save to keep changes.':'This trip is read-only.');}catch(e){if(ticket===epoch)say(text(e),true);}finally{if(ticket===epoch){busy=false;controls();}}}
 async function editActivity(index:number){if(!brief||brief.status!=='draft'||busy||asking)return;const item=shown[index];if(!item||boundary(item))return;const ticket=epoch;busy=true;controls();say('Loading approved places…');try{const r=await db.from('business_listings').select('id,name').eq('destination_id',brief.destination_id).eq('status','approved').in('listing_type',['restaurant','attraction']).order('name').limit(200);if(ticket!==epoch)return;if(r.error)throw r.error;
  const places=field('listing_id') as HTMLSelectElement;places.replaceChildren(new Option('Personal activity / no linked place',''));for(const v of r.data??[])places.add(new Option(v.name,v.id));if(item.listing_id&&!(r.data??[]).some(v=>v.id===item.listing_id))places.add(new Option('Previously selected place (approval must be rechecked)',item.listing_id));
  editing=index;field('activity').value=item.activity;places.value=item.listing_id??'';field('planned_date').value=item.planned_date;(field('planned_date') as HTMLInputElement).min=brief.start_date;(field('planned_date') as HTMLInputElement).max=brief.end_date;field('planned_time').value=item.planned_time.slice(0,5);field('planned_end_time').value=(item.planned_end_time??item.planned_time).slice(0,5);field('notes').value=item.notes??'';get('activity-error').textContent='';editor.showModal();say('Edit the activity, then apply it to the preview.');
 }catch(e){if(ticket===epoch)say(text(e),true);}finally{if(ticket===epoch){busy=false;controls();}}}
 field('listing_id').addEventListener('change',()=>{const select=field('listing_id') as HTMLSelectElement;if(select.value)field('activity').value=select.selectedOptions[0].textContent??'';});
 form.onsubmit=event=>{event.preventDefault();if(!brief||editing<0||brief.status!=='draft')return;const old=shown[editing];if(!old)return;
  const edited:Stop={...old,activity:field('activity').value.trim(),listing_id:field('listing_id').value||null,planned_date:field('planned_date').value,planned_time:field('planned_time').value,planned_end_time:field('planned_end_time').value,notes:field('notes').value,recommendation_reason:'Personally adjusted by the traveler. Confirm opening hours, travel time and costs for this choice.'};
  try{if(edited.planned_end_time<=edited.planned_time)throw Error('An activity must end after it starts.');const candidate=shown.map((x,i)=>i===editing?edited:x);preview=validateSchedule(brief,candidate);render(preview);editor.close();editing=-1;say('Unsaved changes. Review the schedule, including travel gaps, then save it.');}catch(e){get('activity-error').textContent=text(e);}
 };
 get<HTMLButtonElement>('activity-cancel').onclick=()=>editor.close();
 generate.onclick=async()=>{if(!brief||busy||asking)return;const t=brief,ticket=epoch;if(preview&&!await ask('Replace this preview?','Unsaved edits will be replaced with a new generated proposal. Your stored itinerary stays unchanged until you save.','Generate new preview'))return;if(ticket!==epoch)return;busy=true;controls();say('Finding approved places…');try{if(!t.destination_id||!t.start_date||!t.end_date||!t.arrival_time||!t.departure_time)throw Error('Complete the trip brief first.');const r=await db.from('business_listings').select('id,name,listing_type,description,address').eq('destination_id',t.destination_id).eq('status','approved').in('listing_type',['restaurant','attraction']).order('name').limit(200);if(ticket!==epoch)return;if(r.error)throw r.error;if(!r.data?.length)throw Error('No approved restaurants or attractions are available for this destination.');preview=validateSchedule(t,buildItinerary(t,r.data as Venue[]));render(preview);say('Unsaved preview. Edit activities to make it yours, then save. Flexible time indicates limited catalog coverage or available time.');}catch(e){if(ticket===epoch)say(text(e),true);}finally{if(ticket===epoch){busy=false;controls();}}};
 save.onclick=async()=>{if(!brief||!preview||busy||asking)return;const ticket=epoch,t=brief;let items:Stop[];try{items=validateSchedule(t,preview);}catch(e){say(text(e),true);return;}if(!await ask('Save this schedule?','This replaces all existing itinerary items for this trip, including manually added items. No booking or payment will be made.','Save schedule')||ticket!==epoch)return;busy=true;controls();try{const r=await db.rpc('save_my_itinerary',{p_trip:t.id,p_expected_updated_at:t.updated_at,p_items:items});if(ticket!==epoch)return;if(r.error)throw r.error;brief.updated_at=r.data;preview=null;render(items);say('Itinerary saved. Your edits will be here when you reopen it.');}catch(e){if(ticket===epoch)say(text(e),true);}finally{if(ticket===epoch){busy=false;controls();}}};
 async function close(){if(busy||asking)return;const ticket=epoch;if(preview&&!await ask('Discard unsaved changes?','Your saved itinerary will remain unchanged.','Discard changes'))return;if(ticket===epoch)clear();}
 get<HTMLButtonElement>('itinerary-close').onclick=()=>void close();dialog.addEventListener('cancel',e=>{e.preventDefault();void close();});
 const unload=(e:BeforeUnloadEvent)=>{if(preview){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',unload);
 return {open,clear};
}
