// Header, footer and shared dialogs. Pages live in src/pages/.
export const header = `<div class="workspace-bar" data-auth-only><a href="#/home" class="brand">TRAVEL<span>MATE</span></a><span id="workspace-role" class="workspace-badge">Loading role…</span><a href="#/account">My account</a><button id="mobile-menu" type="button" aria-controls="main-navigation" aria-expanded="false">Menu ☰</button></div><header class="top"><a href="#/" class="brand">TRAVEL<span>MATE</span></a>
<div class="top-actions"><a class="plain" href="#/login">Log in</a><a class="btn primary" href="#/register">Get started</a></div></header>
<aside id="main-navigation" class="side-rail" data-auth-only aria-label="Main"><a class="rail-brand" href="#/home" aria-label="TravelMate home">TravelMate<span>YOUR JOURNEY, TOGETHER</span></a><nav class="rail-nav"><a class="rail-btn" href="#/trips" data-nav="/trips"><span aria-hidden="true">✦</span><span>My trips</span></a><a class="rail-btn" href="#/home" data-nav="/home"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M3 21h18M5 21V9l7-6 7 6v12M9 21v-6h6v6"/></svg><span>Home</span></a><a class="rail-btn" href="#/explore" data-nav="/explore"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="12" cy="10" r="3"/><path d="M12 21s7-6.7 7-11.5A7 7 0 0 0 5 9.5C5 14.3 12 21 12 21z"/></svg><span>Explore</span></a><a class="rail-btn" href="#/stay" data-nav="/stay"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M3 19V7a1 1 0 0 1 1-1h5v13M3 19h18M9 19V6M9 10h5a2 2 0 0 1 2 2v7M20 19v-4a2 2 0 0 0-2-2h-2"/></svg><span>Hotels</span></a><a class="rail-btn" href="#/eat" data-nav="/eat"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M6 2v7a2 2 0 0 0 2 2v11M6 2v20M10 2v9M18 2c-2 0-3 2-3 5v3h6M18 2v20"/></svg><span>Eat</span></a><a class="rail-btn" href="#/attractions" data-nav="/attractions"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M12 3l2.8 5.7 6.2.9-4.5 4.4 1 6.2L12 17.3 6.5 20.2l1-6.2L3 9.6l6.2-.9z"/></svg><span>Things to do</span></a><a class="rail-btn" href="#/owner" data-nav="/owner" data-owner-only><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg><span>My business</span></a><a class="rail-btn" href="#/admin" data-nav="/admin" data-admin-only><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M9 11l3 3 8-8M20 12v7a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h9"/></svg><span>Review</span></a><a class="rail-btn" href="#/account" data-nav="/account"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-7 8-7s8 3 8 7"/></svg><span>Profile</span></a><button id="top-logout" class="rail-btn" type="button"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="M16 17l5-5-5-5"/><path d="M21 12H9"/></svg><span>Log out</span></button></nav></aside>`;
export const footer = `<footer><span class="brand">TRAVEL<span>MATE</span></span><span>© 2026 TravelMate — a U-Matter platform</span></footer>`;
export const dialogs = `<dialog id="listing-dialog"><button id="close-listing" type="button" class="quiet">Close</button><div id="listing-detail"></div></dialog>
<dialog id="destination-dialog"><button id="close-detail" class="quiet">Close ×</button><p id="detail-province" class="eyebrow"></p><h2 id="detail-name"></h2><p id="detail-description"></p></dialog>
<dialog id="role-dialog"><p class="eyebrow">ONE LAST STEP</p><h2>How will you use TravelMate?</h2><p>Choose your account type to continue.</p><div class="roles"><button type="button" class="role-card" data-role="traveler"><strong>I'm a Traveler</strong><span>Discover places, save favorites, plan trips and write reviews.</span></button><button type="button" class="role-card" data-role="business_owner"><strong>I'm a Business Owner</strong><span>List and manage your hotel, restaurant, attraction or transport service.</span></button></div><p id="role-error" class="error" role="alert" hidden></p></dialog>
`;
