import { itineraryMarkup, initItinerary } from './itinerary';
import type { SupabaseClient } from '@supabase/supabase-js';
const interests=[['beaches','Beaches','M2 12c2-3 4 3 6 0s4 3 6 0 4 3 6 0M2 18c2-3 4 3 6 0s4 3 6 0 4 3 6 0M12 3v5'],['mountains','Mountains','m3 20 7-15 5 10 3-6 4 11H3Z M8 9l2 2 2-2'],['food','Local food','M4 3v7m3-7v7m3-7v7M7 10v11m12-18c-4 3-4 8 0 8V3m0 8v10'],['nature','Nature','m12 2-7 10h3l-4 6h16l-4-6h3L12 2Zm0 16v4'],['history','Heritage','m3 8 9-5 9 5H3Zm2 3v8m7-8v8m7-8v8M3 21h18'],['adventure','Adventure','m12 3 9 18H3L12 3Zm0 6-3 7 6-3-3-4Z'],['relaxation','Relaxation','M12 21C2 18 2 9 2 9c6 0 10 4 10 12Zm0 0c10-3 10-12 10-12-6 0-10 4-10 12Zm0-4c-5-4-5-9 0-14 5 5 5 10 0 14Z'],['shopping','Shopping','M4 7h16l1 14H3L4 7Zm4 0V5a4 4 0 0 1 8 0v2']] as const;
const icon=(path:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
export const tripsPage = `<section data-page="trips" class="journey-page travel-trip-page" hidden>
<div class="travel-trip-heading"><div><p class="eyebrow">YOUR TRIP, YOUR WAY</p><h1>Let’s plan your next trip.</h1><p>Choose a destination. Add your dates. Make every day yours.</p></div><div class="travel-steps" aria-label="Planning steps"><span class="current"><b>1</b>Trip details</span><span><b>2</b>Day-by-day plan</span></div></div>
<div class="journey-grid"><div class="journey-panel travel-brief"><div class="travel-panel-heading"><h2 id="trip-form-title">Plan a trip</h2><button id="trip-new" type="button">＋ New trip</button></div>
<form id="trip-form"><fieldset id="trip-fields">
<div class="travel-form-section"><h3>${icon('M12 21s8-7 8-12a8 8 0 1 0-16 0c0 5 8 12 8 12Zm0-15a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z')}Where are you going?</h3>
<div class="field-pair travel-destination-fields"><label>Destination<select name="destination_id" required><option value="">Loading destinations…</option></select></label><label>Trip name<input name="name" required maxlength="150" placeholder="e.g. A weekend in La Union"></label></div></div>
<div class="travel-form-section"><h3>${icon('M4 5h16v16H4V5Zm4-3v6m8-6v6M4 10h16')}When’s your trip?</h3><div class="field-pair"><label>Arrival date<input name="start_date" type="date" required></label><label>Departure date<input name="end_date" type="date" required></label></div>
<details class="travel-time-details"><summary>Arrival & departure times <span>Local time · tap to adjust</span></summary><div class="field-pair"><label>Arrival time<input name="arrival_time" type="time" required value="09:00"></label><label>Departure time<input name="departure_time" type="time" required value="18:00"></label></div></details></div>
<div class="travel-form-section"><h3>${icon('M3 7h18v14H3V7Zm0 4h18m-5 4h3M5 7V3h14v4')}Travel essentials</h3><div class="travel-budget-fields"><label>Total budget<input name="budget" type="number" min="0" max="9999999999" step="0.01" required placeholder="10000"></label><label>Currency<select name="budget_currency"><option>PHP</option><option>HKD</option><option>USD</option></select></label><label>Travelers<input name="party_size" type="number" min="1" max="20" value="1" required></label></div><p class="travel-field-title" id="trip-pace-label">Your travel pace</p><select name="travel_pace" hidden><option value="relaxed">Relaxed</option><option value="balanced" selected>Balanced</option><option value="active">Active</option></select><div class="travel-pace-tiles" role="group" aria-labelledby="trip-pace-label">${[['relaxed','Easygoing','Time to unwind'],['balanced','Balanced','A little of everything'],['active','Packed with plans','See more, do more']].map(([key,name,desc])=>`<button type="button" data-pace="${key}" aria-pressed="${key==='balanced'}"><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div></div>
<div class="travel-form-section"><h3>${icon('m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z')}What do you love?</h3><p class="hint" id="trip-interests-help">Tap as many as you like. Your saved preferences are already selected.</p><select name="interests" multiple hidden>${interests.map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select><div class="travel-interest-tiles" role="group" aria-label="Trip interests" aria-describedby="trip-interests-help">${interests.map(([key,name,path])=>`<button type="button" data-interest="${key}" aria-pressed="false">${icon(path)}<span>${name}</span><i aria-hidden="true">✓</i></button>`).join('')}</div></div>
<div id="react-trip-transport" class="tm-react"></div>
<button class="primary trip-submit" type="submit">Review trip & start planning →</button><p class="travel-save-hint">Save your trip, then add places and transport to each day.</p></fieldset></form>
<p id="trip-notice" role="status" aria-live="polite"></p></div>
<aside class="travel-trip-aside"><div id="react-trip-inspiration" class="tm-react"></div>
<div class="journey-panel travel-saved-panel"><div class="travel-panel-heading"><h2>My trips</h2><button id="trip-reload" type="button">Refresh</button></div><div id="trip-list" aria-live="polite">Sign in to load your trips.</div></div></aside></div>
<dialog id="trip-confirm"><form method="dialog"><p class="eyebrow">READY TO SAVE?</p><h2>Check your trip details</h2><p id="trip-summary"></p><p>Your trip will be saved as a draft. No booking or payment will be made.</p><div class="flex gap-4"><button value="cancel">Go back</button><button value="save" class="primary">Save draft</button></div></form></dialog>${itineraryMarkup}</section>`;
const columns='id,name,destination_id,start_date,end_date,arrival_time,departure_time,budget,budget_currency,party_size,travel_pace,interests,status';
type Trip={id:string;name:string;destination_id:string|null;start_date:string|null;end_date:string|null;arrival_time:string|null;departure_time:string|null;budget:number|null;budget_currency:string|null;party_size:number|null;travel_pace:string|null;interests:string[]|null;status:string};
export function initTrips(client:SupabaseClient){
 const itinerary=initItinerary(client);
 const db=client.schema('public'); const form=document.querySelector<HTMLFormElement>('#trip-form')!;
 const fields=document.querySelector<HTMLFieldSetElement>('#trip-fields')!; const list=document.querySelector<HTMLElement>('#trip-list')!;
 const notice=document.querySelector<HTMLElement>('#trip-notice')!; const dialog=document.querySelector<HTMLDialogElement>('#trip-confirm')!;
 let user:string|null=null, editing:string|null=null, epoch=0, busy=false, editable=true; let destinations=new Map<string,string>();
 const field=(name:string)=>form.elements.namedItem(name) as HTMLInputElement|HTMLSelectElement;
 let transportChoice:{destination_id:string;id:string;name:string}|null=null;
 const syncTiles=()=>{for(const b of form.querySelectorAll<HTMLButtonElement>('[data-interest]'))b.setAttribute('aria-pressed',String(Array.from((field('interests') as HTMLSelectElement).selectedOptions).some(o=>o.value===b.dataset.interest)));for(const b of form.querySelectorAll<HTMLButtonElement>('[data-pace]'))b.setAttribute('aria-pressed',String(b.dataset.pace===field('travel_pace').value));};
 const destinationChanged=()=>{transportChoice=null;const id=field('destination_id').value;const [name,province]=(destinations.get(id)??'').split(' · ');window.dispatchEvent(new CustomEvent('travelmate:trip-destination',{detail:{id,name:name||'',province:province||'',disabled:fields.disabled}}));};
 form.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('[data-interest],[data-pace]');if(!b||fields.disabled)return;if(b.dataset.interest){const option=Array.from((field('interests') as HTMLSelectElement).options).find(o=>o.value===b.dataset.interest)!;option.selected=!option.selected;}else field('travel_pace').value=b.dataset.pace!;touched=true;syncTiles();});
 field('destination_id').addEventListener('change',destinationChanged);
 window.addEventListener('travelmate:trip-transport',e=>{const value=(e as CustomEvent).detail;if(!fields.disabled&&value.destination_id===field('destination_id').value)transportChoice=value.id?value:null;});
 let defaults:{interests:string[];travel_pace:string}|null=null,touched=false;
 const applyDefaults=()=>{if(defaults&&!editing&&!touched){field('travel_pace').value=defaults.travel_pace;for(const o of (field('interests') as HTMLSelectElement).options)o.selected=defaults.interests.includes(o.value);}syncTiles();};
 form.addEventListener('input',()=>{touched=true;});form.addEventListener('change',()=>{touched=true;});
 window.addEventListener('travelmate:preferences',event=>{const value=(event as CustomEvent).detail;if(value.profile_id===user){defaults=value;applyDefaults();}});
 const say=(s:string,error=false)=>{notice.textContent=s;notice.classList.toggle('error',error);};
 const reset=()=>{editing=null;editable=true;touched=false;form.reset();applyDefaults();destinationChanged();document.querySelector('#trip-form-title')!.textContent='Plan a trip';};
 function lock(value:boolean){busy=value;fields.disabled=value||!user||!editable;window.dispatchEvent(new CustomEvent('travelmate:trip-lock',{detail:fields.disabled}));document.querySelectorAll<HTMLButtonElement>('#trip-list button,#trip-new,#trip-reload').forEach(b=>b.disabled=value);}
 function failure(e:unknown){const message=e&&typeof e==='object'&&'message' in e?String(e.message):String(e);say(/column|schema cache/.test(message)?'Trip setup is not installed yet. Run database/16_trip_briefs.sql, then refresh.':message,true);}
 async function refresh(){if(!user)return;const id=user,ticket=epoch;lock(true);try{
 const [d,t,p]=await Promise.all([db.from('destinations').select('id,name,province').eq('is_active',1).order('name'),db.from('trips').select(columns).eq('profile_id',id).order('created_at',{ascending:false}).limit(100),db.from('traveler_settings').select('interests,travel_pace').eq('profile_id',id).maybeSingle()]);
 if(ticket!==epoch)return;if(d.error)throw d.error;if(t.error)throw t.error;
 if(!p.error){defaults=p.data;applyDefaults();}
 const selected=field('destination_id').value;destinations=new Map((d.data??[]).map(x=>[x.id,`${x.name} · ${x.province}`]));
 const sel=field('destination_id') as HTMLSelectElement;sel.replaceChildren(new Option('Choose a destination',''));destinations.forEach((label,id)=>sel.add(new Option(label,id)));sel.value=selected;prefill();destinationChanged();
 list.replaceChildren();if(!t.data?.length){list.textContent='No trips yet. Plan your first one here.';return;}
 for(const item of t.data as Trip[]){const card=document.createElement('article');card.className='saved-trip';const title=document.createElement('h3');title.textContent=item.name;const meta=document.createElement('p');meta.textContent=`${item.start_date??'Dates undecided'} → ${item.end_date??'Dates undecided'} · ${item.status}`;const open=document.createElement('button');open.type='button';open.textContent=item.status==='draft'?'Open draft':'View details';open.onclick=()=>{reset();editing=item.id;for(const key of ['name','destination_id','start_date','end_date','arrival_time','departure_time','budget','budget_currency','party_size','travel_pace'] as const)if(item[key]!=null)field(key).value=String(item[key]);for(const o of (field('interests') as HTMLSelectElement).options)o.selected=(item.interests??[]).includes(o.value);editable=item.status==='draft';fields.disabled=!editable;syncTiles();destinationChanged();document.querySelector('#trip-form-title')!.textContent=item.status==='draft'?'Edit trip':'Trip details';say(item.status==='draft'?'Draft loaded. You can update its details.':'This trip is no longer a draft. Its details are read-only in this release.');form.scrollIntoView({behavior:'smooth',block:'start'});};const schedule=document.createElement('button');schedule.type='button';schedule.textContent='View itinerary';schedule.onclick=()=>void itinerary.open(item.id);card.append(title,meta,open,schedule);list.append(card);}
 }catch(e){if(ticket===epoch){list.textContent='Trips could not be loaded.';failure(e);}}finally{if(ticket===epoch)lock(false);}}
 form.onsubmit=async event=>{event.preventDefault();if(!user||busy||!editable)return;
 const val=(n:string)=>field(n).value;const start=val('start_date'),end=val('end_date');
 if(!val('name').trim())return say('Enter a trip name.',true);
 if(end<start||(end===start&&val('departure_time')<=val('arrival_time')))return say('Departure must be after arrival.',true);
 if((Date.parse(end)-Date.parse(start))/86400000>=14)return say('Choose a trip of 1–14 days for the day planner.',true);
 if(!destinations.has(val('destination_id')))return say('Choose a supported destination.',true);
 const payload={name:val('name').trim(),destination_id:val('destination_id'),start_date:start,end_date:end,arrival_time:val('arrival_time'),departure_time:val('departure_time'),budget:Number(val('budget')),budget_currency:val('budget_currency'),party_size:Number(val('party_size')),travel_pace:val('travel_pace'),interests:Array.from((field('interests') as HTMLSelectElement).selectedOptions,o=>o.value)};
 document.querySelector('#trip-summary')!.textContent=`${payload.name} — ${destinations.get(payload.destination_id)}. ${start} at ${payload.arrival_time} to ${end} at ${payload.departure_time}. ${payload.party_size} traveler(s); total budget ${payload.budget_currency} ${payload.budget.toLocaleString()}.`;
 const ticket=epoch,id=user,tripId=editing,selectedTransport=transportChoice;if(selectedTransport)document.querySelector('#trip-summary')!.textContent+=` Transport to review: ${selectedTransport.name}.`;dialog.returnValue='cancel';dialog.showModal();const choice=await new Promise<string>(resolve=>dialog.addEventListener('close',()=>resolve(dialog.returnValue),{once:true}));if(choice!=='save'||ticket!==epoch||busy)return;
 lock(true);try{const result=tripId?await db.from('trips').update(payload).eq('id',tripId).eq('profile_id',id).eq('status','draft').select('id').single():await db.from('trips').insert({...payload,profile_id:id,status:'draft'}).select('id').single();if(ticket!==epoch)return;if(result.error)throw result.error;reset();say('Trip saved. Open it from My trips—even after reloading.');await refresh();if(ticket===epoch&&(!tripId||selectedTransport))itinerary.open(result.data.id,selectedTransport?.id);}catch(e){if(ticket===epoch)failure(e);}finally{if(ticket===epoch)lock(false);}
 };
 document.querySelector<HTMLButtonElement>('#trip-new')!.onclick=()=>{if(busy)return;reset();lock(false);say('Start a new trip.');};document.querySelector<HTMLButtonElement>('#trip-reload')!.onclick=()=>void refresh();
 const prefill=()=>{const destination=sessionStorage.getItem('travelmate:plan-destination');if(!destination)return;const select=field('destination_id') as HTMLSelectElement;if([...select.options].some(o=>o.value===destination)){select.value=destination;sessionStorage.removeItem('travelmate:plan-destination');say('Destination selected. Add your dates and travel style to continue.');destinationChanged();}};
 window.addEventListener('travelmate:new-trip',()=>{if(busy)return;reset();lock(false);prefill();form.scrollIntoView({behavior:'smooth',block:'start'});});
 window.addEventListener('hashchange',()=>{if(location.hash==='#/trips')prefill();});
 return {setUser(id:string|null){itinerary.clear();epoch++;defaults=null;user=id;reset();if(dialog.open)dialog.close('cancel');list.replaceChildren();say('');lock(false);if(id)void refresh();else list.textContent='Sign in to load your trips.';}};
}
